# Run after `pnpm build` and `pnpm tauri build --debug --no-bundle`.
#
# `TASK-0044` — product acceptance of the PER-BRAIN RESUME STATE (`DEC-0042`) in the real
# WebView2 host. The three trees are generated by `task0044-seed-proof.py` under the proof root
# and die with it. **No personal folder is ever involved.**
#
# Three real launches of the same executable against the SAME sandbox variant, with a REAL close
# between them and the source changed while the application is closed:
#
#   phase 1  baseline; brains X, Y and Z each given a DIFFERENT branch, selection, filter, camera
#            and details panel through real mouse events; X -> Y -> Z -> X -> Z -> Y in one
#            session, every return compared value by value; a wheel burst counted on the wire
#   (real close of the application)
#   phase 2  relaunch: the last active brain (Y) comes back ALONE with its state; Z and X are
#            visited and each is exactly what it was; Actualiser keeps the state
#   (real close of the application; phase 0 changes the source while it is CLOSED)
#   phase 3  relaunch: the deleted selection of X and of Y falls back to a valid target, the
#            filter stays, nothing stale is kept, Z is untouched
#
# The cadences of the watcher are shortened by the development-only overrides (never in a
# release build), so the proof does not wait five real seconds for each root-guard tick.
[CmdletBinding()]
param([int]$Port = 9344)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository

$variant = 'task0044-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null

$seedJson = python scripts/task0044-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic trees/catalogue preparation failed' }

$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:FILETOPO_WATCH_GUARD_MS = '500'
$env:FILETOPO_WATCH_COALESCE_MS = '150'
$env:FILETOPO_WATCH_CALM_MS = '150'
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'

function Stop-Application {
    param($Application)
    # A REAL close: the window is asked first, the process only stopped if it refuses — and
    # it is the process this script just started.
    if (-not $Application.HasExited) {
        $null = $Application.CloseMainWindow()
        if (-not $Application.WaitForExit(20000)) {
            Write-Host "TASK-0044: la fenetre n'a pas repondu, arret du processus demarre ici"
            Stop-Process -Id $Application.Id -ErrorAction SilentlyContinue
        }
    }
    $Application.WaitForExit()
}

function Invoke-Phase {
    param([int]$Phase)
    Write-Host "TASK-0044: passe $Phase - demarrage reel de l'application"
    $application = Start-Process -FilePath $executable -PassThru -WindowStyle Hidden -WorkingDirectory $repository `
        -RedirectStandardOutput (Join-Path $proofRoot "app-phase$Phase.log") -RedirectStandardError (Join-Path $proofRoot "app-error-phase$Phase.log")
    try {
        # The seed travels on stdin, not the command line: the absolute paths are search
        # keys for the harness, never values it exposes.
        $errorFile = Join-Path $proofRoot "harness-error-phase$Phase.txt"
        $seedJson | node scripts/task0044-webview2.mjs $Port $variant $Phase 2> $errorFile
        if ($LASTEXITCODE -ne 0) {
            Get-Content -LiteralPath $errorFile -ErrorAction SilentlyContinue | Select-Object -First 30 | ForEach-Object { Write-Host $_ }
            throw "TASK-0044: WebView2 proof failed at phase $Phase; inspect $proofRoot"
        }
    } finally {
        Stop-Application -Application $application
    }
}

Invoke-Phase -Phase 1
Start-Sleep -Seconds 2
Invoke-Phase -Phase 2
Start-Sleep -Seconds 2

# Phase 0 — the application is CLOSED; the source moves on.
Write-Host 'TASK-0044: application fermee - le harnais modifie la source'
$seedJson | node scripts/task0044-webview2.mjs $Port $variant 0
if ($LASTEXITCODE -ne 0) { throw 'TASK-0044: the offline mutation failed' }
Start-Sleep -Seconds 1

Invoke-Phase -Phase 3

$phase1 = Get-Content (Join-Path $proofRoot 'phase1.json') -Raw | ConvertFrom-Json
$phase2 = Get-Content (Join-Path $proofRoot 'phase2.json') -Raw | ConvertFrom-Json
$phase3 = Get-Content (Join-Path $proofRoot 'phase3.json') -Raw | ConvertFrom-Json
$fatal = 0
foreach ($n in 1, 2, 3) { $fatal += [int](Get-Content (Join-Path $proofRoot "phase$n-fatal-count.json") -Raw) }
if ($fatal -ne 0) { throw "TASK-0044: $fatal fatal console error(s) across the three phases" }

function Get-Record($state) {
    # Only ids, numbers, closed words and booleans.
    [ordered]@{
        focusNodeId        = $state.focusNodeId
        selectedNodeId     = $state.selectedNodeId
        view               = if ($null -eq $state.view) { $null } else { [ordered]@{ scale = $state.view.scale; tx = $state.view.tx; ty = $state.view.ty } }
        filter             = [ordered]@{ state = $state.filter.state; kinds = @($state.filter.kinds); availability = $state.filter.availability }
        detailsPanelVisible = $state.detailsPanelVisible
    }
}

$artifact = [ordered]@{
    task = 'TASK-0044'
    status = 'NONCANONICAL_ENGINEERING_EVIDENCE'
    engine = 'Windows Tauri / real WebView2'
    source = 'three REAL_ROOT brains registered internally (task0044-seed-proof.py). Every interaction is a real mouse event dispatched through the browser input pipeline (CDP Input.dispatchMouseEvent): clicks, real wheel notches, a real drag. Every logical value is read back from the catalogue (map_brain_resume_state) and from the real screen; the resume writes the product itself makes are counted on the wire (CDP Network). Two REAL closes of the process, the source changed while the application is closed.'
    realProcessRestarts = 2
    tree = [ordered]@{
        generatedByTheProofNotByTheUser = $true
        personalDataUsed               = $false
        brains                         = 3
        docsNodeIdSharedByTheThreeBrains = [int]$phase1.sharedDocsId
    }
    statesGivenThroughTheRealUi = [ordered]@{
        X = Get-Record $phase1.expected.X.record
        Y = Get-Record $phase1.expected.Y.record
        Z = Get-Record $phase1.expected.Z.record
        selectedMatchOfXWasBeyondThePageOne = $true
        selectedMatchOfZWasBeyondThePageOne = $true
        theSameNumericIdMeansTwoThings      = "X.focusNodeId == Y.selectedNodeId == $($phase1.sharedDocsId)"
    }
    inOneSession = [ordered]@{
        cycle = @($phase1.sessionCycle)
        everyReturnEqualsWhatWasLeft = $true
        indexAndJournalUntouchedByResumeWrites = [bool]$phase1.indexAndJournalUntouchedByResumeWrites
        wheelBurst = $phase1.wheelBurst
    }
    afterTheFirstRealClose = [ordered]@{
        lastActiveBrainReopenedAlone   = [string]$phase2.reopenedAlone
        yEqualsWhatWasLeft             = $true
        zEqualsWhatWasLeft             = $true
        xEqualsWhatWasLeft             = $true
        actualiserKeepsTheState        = [bool]$phase2.actualiserKeepsTheState
        recordsAfterRestart = [ordered]@{
            X = Get-Record $phase2.recordsAfterRestart.X
            Y = Get-Record $phase2.recordsAfterRestart.Y
            Z = Get-Record $phase2.recordsAfterRestart.Z
        }
    }
    afterTheOfflineDeletionAndTheSecondRealClose = [ordered]@{
        xDeletedSelectionFellBack = $phase3.X
        yDeletedDirectoryFellBack = $phase3.Y
        zExactlyWhatItWas         = [bool]$phase3.ZExactAfterOffline
    }
    resumeWritesMadeByTheProductOnTheWire = [ordered]@{
        phase1 = [ordered]@{ writes = [int]$phase1.resumeWritesOnTheWire; bodiesInspected = [int]$phase1.resumeWriteBodiesInspected }
        phase2 = [ordered]@{ writes = [int]$phase2.resumeWritesOnTheWire; bodiesInspected = [int]$phase2.resumeWriteBodiesInspected }
        phase3 = [ordered]@{ writes = [int]$phase3.resumeWritesOnTheWire; bodiesInspected = [int]$phase3.resumeWriteBodiesInspected }
        eachBodyChecked = 'no absolute path, no filter cursor, no name; the closed five-key state'
    }
    noFilterCursorEverStored = $true
    fatalConsoleErrors = $fatal
    limits = @(
        'No personal brain: the analysed trees were generated by task0044-seed-proof.py and die with the proof root',
        'The closes are normal ones (the window is asked to close); the resume state is not claimed to survive a crash of the process: a change made within the last debounce window (250 ms) of a hard kill is not guaranteed',
        'Real mouse events are dispatched through the browser input pipeline by the harness (CDP); a physical mouse, touch or keyboard-only navigation is not exercised here',
        'The persistent state covers a single brain on screen: a composition of several brains is still session-only (DEC-0042 section 7), and the camera of a composition is not stored for any one brain',
        'After Reconstruire a stored node id is checked for existence only: a rebuilt Index may give an old id to another node (Actualiser keeps identities and is the covered path)',
        'P-19 stays partial: no FR/EN choice, no accessibility preferences, no legend preference and no multi-brain composition persistence in this slice',
        'Development workstation, local NTFS disk; not a modest-laptop acceptance test'
    )
}

$artifact | ConvertTo-Json -Depth 8 | Set-Content -Path (Join-Path $repository 'docs/performance/runs/TASK-0044-webview2.json')
Write-Output 'TASK-0044: real launches complete; artefact written to docs/performance/runs/TASK-0044-webview2.json'
