# Run after `pnpm build` and `pnpm tauri build --debug --no-bundle`.
#
# `TASK-0045` — product acceptance of the BRAIN IDENTITY EDITOR (`DEC-0043`) in the real WebView2
# host. The two trees are generated by `task0045-seed-proof.py` under the proof root and die with
# it. **No personal folder is ever involved.**
#
# Two real launches of the same executable against the SAME sandbox variant, with a REAL close
# between them:
#
#   phase 1  three brains (two of them on ONE folder), each given its own resume state through
#            real clicks; brain A edited with the keyboard, brain B with the mouse, brain C
#            cancelled and refused; every other brain, the source, the Index, the journal and every
#            resume record compared after each step; the product's own IPC calls read from the wire
#   (real close of the application)
#   phase 2  relaunch: A comes back alone with its NEW identity and its resume state; B and C are
#            visited; nothing rewrote the catalogue; the editor reopens on the persisted values
#
# The cadences of the watcher are shortened by the development-only overrides (never in a release
# build). The window is NOT hidden: the phase-1 save is a key sent through the operating system,
# which needs a window that can be brought forward.
[CmdletBinding()]
param([int]$Port = 9345)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository

$variant = 'task0045-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null

$seedJson = python scripts/task0045-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic trees/catalogue preparation failed' }

$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:FILETOPO_WATCH_GUARD_MS = '500'
$env:FILETOPO_WATCH_COALESCE_MS = '150'
$env:FILETOPO_WATCH_CALM_MS = '150'
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'

function Stop-Application {
    param($Application)
    # A REAL close: the window is asked first, the process only stopped if it refuses — and
    # it is the process this script just started.
    if (-not $Application.HasExited) {
        $null = $Application.CloseMainWindow()
        if (-not $Application.WaitForExit(20000)) {
            Write-Host "TASK-0045: la fenetre n'a pas repondu, arret du processus demarre ici"
            Stop-Process -Id $Application.Id -ErrorAction SilentlyContinue
        }
    }
    $Application.WaitForExit()
}

function Invoke-Phase {
    param([int]$Phase)
    Write-Host "TASK-0045: passe $Phase - demarrage reel de l'application"
    $application = Start-Process -FilePath $executable -PassThru -WorkingDirectory $repository `
        -RedirectStandardOutput (Join-Path $proofRoot "app-phase$Phase.log") -RedirectStandardError (Join-Path $proofRoot "app-error-phase$Phase.log")
    try {
        # The seed travels on stdin, not the command line: the absolute paths are search keys for
        # the harness, never values it exposes.
        $errorFile = Join-Path $proofRoot "harness-error-phase$Phase.txt"
        $seedJson | node scripts/task0045-webview2.mjs $Port $variant $Phase 2> $errorFile
        if ($LASTEXITCODE -ne 0) {
            Get-Content -LiteralPath $errorFile -ErrorAction SilentlyContinue | Select-Object -First 30 | ForEach-Object { Write-Host $_ }
            throw "TASK-0045: WebView2 proof failed at phase $Phase; inspect $proofRoot"
        }
    } finally {
        Stop-Application -Application $application
    }
}

Invoke-Phase -Phase 1
Start-Sleep -Seconds 2
Invoke-Phase -Phase 2

$phase1 = Get-Content (Join-Path $proofRoot 'phase1.json') -Raw | ConvertFrom-Json
$phase2 = Get-Content (Join-Path $proofRoot 'phase2.json') -Raw | ConvertFrom-Json
$fatal = 0
foreach ($n in 1, 2) { $fatal += [int](Get-Content (Join-Path $proofRoot "phase$n-fatal-count.json") -Raw) }
if ($fatal -ne 0) { throw "TASK-0045: $fatal fatal console error(s) across the two phases" }

function Get-Identity($record) {
    [ordered]@{ displayName = $record.displayName; color = $record.color; icon = $record.icon }
}

$artifact = [ordered]@{
    task = 'TASK-0045'
    status = 'NONCANONICAL_ENGINEERING_EVIDENCE'
    engine = 'Windows Tauri / real WebView2'
    source = 'three REAL_ROOT brains registered internally (task0045-seed-proof.py), brains A and C reading the SAME folder. Mouse and key events are dispatched through the browser input pipeline (CDP Input.dispatchMouseEvent / Input.dispatchKeyEvent); the save of edit 1 is a key sent through the operating system when the window could be brought forward. Every logical value is read back from the catalogue (map_brains, map_brain_resume_state) and from the real screen; the product''s own IPC calls are read from the wire (CDP Network). One REAL close of the process.'
    realProcessRestarts = 1
    tree = [ordered]@{
        generatedByTheProofNotByTheUser = $true
        personalDataUsed               = $false
        brains                         = 3
        brainsSharingOneFolder         = 'A and C (same sourceRef, same sourceLabel, different brainId)'
    }
    identitiesBefore = [ordered]@{
        A = $phase1.startingIdentities.A
        B = $phase1.startingIdentities.B
        C = $phase1.startingIdentities.C
    }
    identitiesAtClose = [ordered]@{
        A = Get-Identity $phase1.atClose.records.A
        B = Get-Identity $phase1.atClose.records.B
        C = Get-Identity $phase1.atClose.records.C
    }
    edit1 = $phase1.edit1
    edit2 = $phase1.edit2
    cancelAndRefusedEntry = $phase1.cancelAndRefusedEntry
    backendRefusalsProbedDirectly = @($phase1.backendRefusals | ForEach-Object { $_.case })
    resumeStatesGivenThroughTheRealUi = $phase1.resumeStatesGiven
    afterTheRealClose = [ordered]@{
        reopenedAlone = [string]$phase2.reopenedAlone
        screen = $phase2.afterRestart
        editorReopensOnPersistedValues = [bool]$phase2.editorReopensOnPersistedValues
        afterVisitingTheOtherBrains = $phase2.afterVisiting
        productSentNoIdentityWriteInPhase2 = $true
    }
    checkedAfterEveryEdit = @(
        'the other brains: the whole catalogue record, bit for bit (including the brain that shares the source)',
        'the edited brain: brainId, sourceKind, sourceRef, sourceLabel and position unchanged',
        'the source: name, size, date and SHA-256 of every file and directory under both roots',
        'the Index and the journal: revision, node count and journal total of every brain',
        'the resume record of every brain, and the active brain',
        'the product''s own IPC calls: exactly one map_brain_update, no map_open / map_view / map_refresh / map_rebuild / resume write / journal call'
    )
    fatalConsoleErrors = $fatal
    limits = @(
        'No personal brain: the analysed trees were generated by task0045-seed-proof.py and die with the proof root',
        'The native colour picker is an operating-system dialog that neither the page nor CDP can drive: the colour is set through the page''s value setter and the real input event; name and icon are typed with real key events',
        'Mouse and key events are dispatched through the browser input pipeline by the harness (CDP); only the edit-1 save may be an operating-system key, as edit1.saveKeyPath states',
        'The close is a normal one (the window is asked to close); no claim about a crash of the process',
        'F-036 / WCAG 2.2 AA is not claimed: this proves the form works with the keyboard and that the name and the icon stay visible with the colour, nothing more',
        'F-035 FR/EN is not started; P-19 stays partial',
        'Development workstation, local NTFS disk; not a modest-laptop acceptance test'
    )
}

$artifact | ConvertTo-Json -Depth 8 | Set-Content -Path (Join-Path $repository 'docs/performance/runs/TASK-0045-webview2.json')
Write-Output 'TASK-0045: real launches complete; artefact written to docs/performance/runs/TASK-0045-webview2.json'
