# Run after pnpm build and cargo build.
#
# `TASK-0042` — product acceptance of the source-availability foundation
# (`F-032`, `DEC-0040`) in the real WebView2 host. The tree is generated by
# `task0042-seed-proof.py` under the proof root and dies with it. **No personal
# folder is ever involved.**
#
# Two real launches of the same executable against the SAME sandbox variant (same
# brain index and catalogue, so the observation genuinely persists):
#
#   phase 1  baseline (SYNCED) -> unchanged Actualiser (no-op) -> one change ->
#            the harness MOVES THE WHOLE ROOT out of its path -> ONE real
#            Actualiser fails cleanly: the map stays, the badge says UNAVAILABLE,
#            revision/journal/projection/index id unchanged
#   (real close, real restart — the source is STILL absent)
#   phase 2  Ouvrir shows the map and the persisted UNAVAILABLE without touching the
#            source -> the harness puts the SAME folder back -> Actualiser is an
#            incremental no-op, SYNCED -> a DIFFERENT root at the same path is
#            refused (SOURCE_CHANGED) and Reconstruire accepts it
[CmdletBinding()]
param([int]$Port = 9342)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository

$variant = 'task0042-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null

$seedJson = python scripts/task0042-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic tree/catalogue preparation failed' }

$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'

function Invoke-Phase {
    param([int]$Phase)
    Write-Host "TASK-0042: passe $Phase - demarrage reel de l'application"
    $application = Start-Process -FilePath $executable -PassThru -WindowStyle Hidden -WorkingDirectory $repository `
        -RedirectStandardOutput (Join-Path $proofRoot "app-phase$Phase.log") -RedirectStandardError (Join-Path $proofRoot "app-error-phase$Phase.log")
    try {
        # The seed travels on stdin, not the command line: the absolute paths are
        # search keys for the harness, never values it exposes.
        $errorFile = Join-Path $proofRoot "harness-error-phase$Phase.txt"
        $seedJson | node scripts/task0042-webview2.mjs $Port $variant $Phase 2> $errorFile
        if ($LASTEXITCODE -ne 0) {
            Get-Content -LiteralPath $errorFile -ErrorAction SilentlyContinue | Select-Object -First 30 | ForEach-Object { Write-Host $_ }
            throw "TASK-0042: WebView2 proof failed at phase $Phase; inspect $proofRoot"
        }
    } finally {
        # A REAL close: the window is asked first, the process only stopped if it
        # refuses — and it is the process this script just started.
        if (-not $application.HasExited) {
            $null = $application.CloseMainWindow()
            if (-not $application.WaitForExit(15000)) {
                Write-Host "TASK-0042: la fenetre n'a pas repondu, arret du processus demarre ici"
                Stop-Process -Id $application.Id -ErrorAction SilentlyContinue
            }
        }
        $application.WaitForExit()
    }
}

Invoke-Phase -Phase 1
Start-Sleep -Seconds 2
Invoke-Phase -Phase 2

$phase1 = Get-Content (Join-Path $proofRoot 'phase1.json') -Raw | ConvertFrom-Json
$phase2 = Get-Content (Join-Path $proofRoot 'phase2.json') -Raw | ConvertFrom-Json
$fatal1 = [int](Get-Content (Join-Path $proofRoot 'phase1-fatal-count.json') -Raw)
$fatal2 = [int](Get-Content (Join-Path $proofRoot 'phase2-fatal-count.json') -Raw)
$totalFatal = $fatal1 + $fatal2
if ($totalFatal -ne 0) {
    throw "TASK-0042: $totalFatal fatal console error(s) across the two phases"
}

# Only synthetic ids, counters, closed words and booleans.
$artifact = [ordered]@{
    task = 'TASK-0042'
    status = 'NONCANONICAL_ENGINEERING_EVIDENCE'
    engine = 'Windows Tauri / real WebView2'
    source = 'one REAL_ROOT brain registered internally (task0042-seed-proof.py) -> the harness moves the whole root out of its path, outside the process -> real Actualiser click refused -> badge read back from the backend (map_source_observation) -> REAL process restart with the source still absent -> Ouvrir shows the map and the persisted observation -> the same folder put back -> real Actualiser -> a different root at the same path -> refused, then Reconstruire; the outcome of each IPC is read from the Tauri-Response header on the wire (CDP Network), every state from the real badge and panels'
    realProcessRestarts = 1
    tree = [ordered]@{
        generatedByTheProofNotByTheUser = $true
        personalDataUsed               = $false
        brains                         = 1
    }
    beforeTheAbsence = [ordered]@{
        baselineIsSynced                   = [bool]$phase1.baselineIsSynced
        unchangedIsSyncedNoOp              = [bool]$phase1.unchangedIsSyncedNoOp
    }
    duringTheAbsence = [ordered]@{
        actualiserFailedCleanly            = [bool]$phase1.actualiserFailedCleanly
        badgeReadFromBackendWithoutReopening = [bool]$phase1.badgeReadFromBackendWithoutReopening
        badgeSaysUnavailable               = [bool]$phase1.badgeSaysUnavailable
        mapStaysOnScreen                   = [bool]$phase1.mapStaysOnScreen
        localActionsStillWork              = [bool]$phase1.localActionsStillWork
        indexUntouchedByTheAbsence         = [bool]$phase1.indexUntouchedByTheAbsence
        noDeletionInvented                 = [bool]$phase1.noDeletionInvented
    }
    afterRealRestartSourceStillAbsent = [ordered]@{
        sourceStillAbsentAtRestart         = [bool]$phase2.sourceStillAbsentAtRestart
        nothingBuiltAtStartup              = [bool]$phase2.nothingBuiltAtStartup
        openedWithoutTheSource             = [bool]$phase2.openedWithoutTheSource
        sameIndexAfterRestart              = [bool]$phase2.sameIndexAfterRestart
        sameObservationAfterRestart        = [bool]$phase2.sameObservationAfterRestart
    }
    afterTheSameFolderIsPutBack = [ordered]@{
        recoveryIsIncrementalNoOp          = [bool]$phase2.recoveryIsIncrementalNoOp
        recoveryInventedNothing            = [bool]$phase2.recoveryInventedNothing
    }
    aDifferentRootAtTheSamePath = [ordered]@{
        replacedRootIsSourceChanged        = [bool]$phase2.replacedRootIsSourceChanged
        reconstruireAcceptsTheNewRoot      = [bool]$phase2.reconstruireAcceptsTheNewRoot
    }
    noAbsolutePathOrIdentityLeakPhase1 = [bool]$phase1.noAbsolutePathOrIdentityLeak
    noAbsolutePathOrIdentityLeakPhase2 = [bool]$phase2.noAbsolutePathOrIdentityLeak
    fatalConsoleErrors                 = $totalFatal
    limits = @(
        'No personal brain: the analysed tree was generated by task0042-seed-proof.py and dies with the proof root',
        'The absence is a folder MOVED away from its path by the harness (a real ROOT_NOT_FOUND); a permission-denied root, an unplugged drive or a network share are not fabricated — their classification is proved at the Rust level on closed reasons only',
        'SCAN_INCOMPLETE and APPLY_FAILED are dangerous or artificial to provoke in the real host and are proved at the Rust level (source_availability_tests: a directory vanishing during the scan, fixture drift, an injected SQL failure with exact rollback)',
        'The badge states the LAST observation. Nothing here observes the source in the background: detection stays manual, and no watcher or polling exists (F-030 is out of scope), so F-032 is a foundation, not a completed feature',
        'Development workstation; not a modest-laptop acceptance test'
    )
}

$artifact | ConvertTo-Json -Depth 6 | Set-Content -Path (Join-Path $repository 'docs/performance/runs/TASK-0042-webview2.json')
Write-Output 'TASK-0042: real launches complete; artefact written to docs/performance/runs/TASK-0042-webview2.json'
