"""Fresh REAL_ROOT catalogue and a large nested synthetic tree — TASK-0033.

Nothing here is anybody's data. The tree is generated by this script, under
the proof root, specifically shaped to exercise the three things `TASK-0033`
changed and that unit tests alone cannot prove inside a real WebView2 host:

* a directory whose direct children are **only** directories, more than the
  64-block ordinary target (`A`) — a pure-kind overflow;
* a directory whose direct children **mix** directories and files, more than
  the target (`B`) — the actual directory-first competition;
* a directory with thousands of flat files and nothing else (`C`) — files
  filling the target when no directory competes, and a long
  pagination/aggregate chain;
* a single-child chain many levels deep (`D`) — ancestry staying
  materialized past the ordinary target.

Names are kept deliberately short: at 25 levels the fully-qualified path
under a real checkout can exceed Windows' legacy `MAX_PATH` (260 characters)
long before this proof's own depth target does anything interesting, so
every segment here counts.

The registration is written directly to a fresh sandbox variant's catalogue,
exactly as `task0032-seed-proof.py` does, for the same reason: `TASK-0033`
proves the product path **after** internal registration, not a fragile
automation of the native folder dialogue — that dialogue itself is `TASK-0032`
`RR2`'s job, not this one's.
"""

import json
import sqlite3
import sys
import uuid
from pathlib import Path

repository = Path(__file__).resolve().parent.parent
variant = sys.argv[1]
assert variant.startswith("task0033-") and variant.replace("-", "").isalnum()

proof_root = repository / ".filetopo-sandbox" / variant
state_root = repository / ".filetopo-sandbox" / "variants" / variant

# A sibling of the FileTopo state space, never an ancestor or a descendant of
# it — `DEC-0033` G's containment rule. Named `t`, not something descriptive,
# to leave the path budget to the depth this proof actually needs.
source_root = proof_root / "t"
source_root.mkdir(parents=True, exist_ok=False)

TARGET_TOTAL = 5_200
DEEP_LEVELS = 15
count = 0


def touch(path: Path, content: str) -> None:
    global count
    path.write_text(content, encoding="utf-8")
    count += 1


def mkdir(path: Path) -> None:
    global count
    path.mkdir(parents=True, exist_ok=False)
    count += 1


# --- A. pure-directory overflow: 120 subdirectories, no files at this level.
a_root = source_root / "A"
mkdir(a_root)
for i in range(120):
    branch = a_root / f"d{i:03d}"
    mkdir(branch)
    for n in range(4):
        touch(branch / f"f{n}.txt", f"synthetique A {i} {n}\n")

# --- B. mixed overflow: 40 directories AND 90 files as direct children.
b_root = source_root / "B"
mkdir(b_root)
for i in range(40):
    branch = b_root / f"d{i:02d}"
    mkdir(branch)
    for n in range(2):
        touch(branch / f"f{n}.txt", f"synthetique B-dir {i} {n}\n")
for i in range(90):
    touch(b_root / f"f{i:03d}.txt", f"synthetique B-file {i}\n")

# --- D. a single-child chain, DEEP_LEVELS levels deep, one file per level.
d_root = source_root / "D"
mkdir(d_root)
prefix = d_root
for level in range(1, DEEP_LEVELS + 1):
    prefix = prefix / f"{level:02d}"
    mkdir(prefix)
    touch(prefix / "n.txt", f"synthetique D niveau {level}\n")

# --- C. flat pile of files, sized to bring the whole tree past TARGET_TOTAL.
c_root = source_root / "C"
mkdir(c_root)
remaining = max(200, TARGET_TOTAL - count)
for i in range(remaining):
    touch(c_root / f"e{i:05d}.txt", f"synthetique C {i}\n")

# --- a few loose files directly under the root, for variety.
for i in range(5):
    touch(source_root / f"r{i}.txt", f"synthetique racine {i}\n")

canonical = source_root.resolve()

brains = state_root / "brains"
brains.mkdir(parents=True, exist_ok=False)
brain_id = "real-" + str(uuid.uuid4())
source_ref = str(uuid.uuid4())
with sqlite3.connect(brains / "catalog.sqlite") as db:
    db.execute(
        """CREATE TABLE brains (
             brain_id TEXT PRIMARY KEY CHECK(length(brain_id) > 0),
             display_name TEXT NOT NULL CHECK(length(trim(display_name)) > 0),
             color TEXT NOT NULL CHECK(length(color) = 7 AND substr(color, 1, 1) = '#'),
             icon TEXT NOT NULL CHECK(length(icon) > 0),
             source_kind TEXT NOT NULL CHECK(source_kind IN ('SYNTHETIC_FIXTURE', 'REAL_ROOT')),
             source_ref TEXT NOT NULL CHECK(length(source_ref) > 0),
             source_label TEXT NOT NULL CHECK(length(source_label) > 0),
             source_path BLOB,
             position INTEGER NOT NULL,
             CHECK ((source_kind = 'REAL_ROOT') = (source_path IS NOT NULL))
           )"""
    )
    db.execute("CREATE TABLE catalog_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)")
    db.execute(
        "INSERT INTO brains VALUES (?,?,?,?,?,?,?,?,?)",
        (
            brain_id,
            "Arbre topographique de test",
            "#2F6DA8",
            "▣",
            "REAL_ROOT",
            source_ref,
            source_root.name,
            str(canonical).encode("utf-16-le"),
            4,
        ),
    )
    db.execute("INSERT INTO catalog_meta VALUES ('active_brain_id', ?)", (brain_id,))
    db.execute("INSERT INTO catalog_meta VALUES ('schema_version', '2')")
    db.execute("PRAGMA user_version=2")

print(
    json.dumps(
        {
            "brainId": brain_id,
            "sourceRef": source_ref,
            "sourceLabel": source_root.name,
            "absolutePath": str(canonical),
            "entriesWritten": count,
            "deepLevels": DEEP_LEVELS,
        }
    )
)
