"""Fresh REAL_ROOT catalogue and test tree for the real WebView2 proof.

Two things are prepared here, and neither of them is anybody's data:

* a **temporary tree**, generated by this script under the proof root, with
  Unicode names and more than one level. It is created here rather than by the
  application, because `TASK-0032` has to show FileTopo reading a folder it did
  **not** make;
* a **schema-2 catalogue** holding one `REAL_ROOT` brain bound to that tree.

The registration is written directly rather than driven through the native
dialogue: `TASK-0032` §7 asks the host pass to prove the product path **after
internal registration**, and explicitly does not ask for a fragile automation
of a Windows modal. What the dialogue command itself does — validation,
canonicalisation, one row, no scan — is proved by `RR2` in Rust.

The absolute path is stored exactly as `map::brains` stores it: a UTF-16LE
`BLOB`, never a `TEXT` column — `DEC-0033` C.
"""

import json
import sqlite3
import sys
import uuid
from pathlib import Path

repository = Path(__file__).resolve().parent.parent
variant = sys.argv[1]
assert variant.startswith("task0032-") and variant.replace("-", "").isalnum()

proof_root = repository / ".filetopo-sandbox" / variant
state_root = repository / ".filetopo-sandbox" / "variants" / variant

# A sibling of the FileTopo state space, never an ancestor or a descendant of
# it — the containment rule of `DEC-0033` G refuses those, and `RR8` proves it.
source_root = proof_root / "arbre-de-test"
source_root.mkdir(parents=True, exist_ok=False)

# Wide enough that the bounded projection has something to bound: the view
# budget is 512 entities and this tree carries well over a thousand nodes.
FOLDERS = ["Dossier accentué", "漢字フォルダ", "notes-2026", "archives"]
files_written = 0
for index, folder in enumerate(FOLDERS):
    branch = source_root / folder / f"sous-dossier-{index}"
    branch.mkdir(parents=True)
    for n in range(300):
        (branch / f"document-{n:03d}-éàü.txt").write_text(
            f"contenu synthetique {folder} {n}\n", encoding="utf-8"
        )
        files_written += 1
(source_root / "racine.txt").write_text("racine synthetique\n", encoding="utf-8")
files_written += 1

canonical = source_root.resolve()

brains = state_root / "brains"
brains.mkdir(parents=True, exist_ok=False)
brain_id = "real-" + str(uuid.uuid4())
source_ref = str(uuid.uuid4())
with sqlite3.connect(brains / "catalog.sqlite") as db:
    db.execute(
        """CREATE TABLE brains (
             brain_id TEXT PRIMARY KEY CHECK(length(brain_id) > 0),
             display_name TEXT NOT NULL CHECK(length(trim(display_name)) > 0),
             color TEXT NOT NULL CHECK(length(color) = 7 AND substr(color, 1, 1) = '#'),
             icon TEXT NOT NULL CHECK(length(icon) > 0),
             source_kind TEXT NOT NULL CHECK(source_kind IN ('SYNTHETIC_FIXTURE', 'REAL_ROOT')),
             source_ref TEXT NOT NULL CHECK(length(source_ref) > 0),
             source_label TEXT NOT NULL CHECK(length(source_label) > 0),
             source_path BLOB,
             position INTEGER NOT NULL,
             CHECK ((source_kind = 'REAL_ROOT') = (source_path IS NOT NULL))
           )"""
    )
    db.execute("CREATE TABLE catalog_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)")
    db.execute(
        "INSERT INTO brains VALUES (?,?,?,?,?,?,?,?,?)",
        (
            brain_id,
            "Arbre de test",
            "#2F6DA8",
            "●",
            "REAL_ROOT",
            source_ref,
            source_root.name,
            # UTF-16LE, the exact encoding `crate::path_codec` reads back.
            str(canonical).encode("utf-16-le"),
            4,
        ),
    )
    db.execute("INSERT INTO catalog_meta VALUES ('active_brain_id', ?)", (brain_id,))
    db.execute("INSERT INTO catalog_meta VALUES ('schema_version', '2')")
    db.execute("PRAGMA user_version=2")

# Handed to the Node harness on stdout. The absolute path travels here because
# the harness has to *look for it* in every DTO; it is never written to an
# artefact — `TASK-0032` §6 records the verdict, not the sentinel.
print(
    json.dumps(
        {
            "brainId": brain_id,
            "sourceRef": source_ref,
            "sourceLabel": source_root.name,
            "absolutePath": str(canonical),
            "filesWritten": files_written,
        }
    )
)
