# Run after pnpm build and cargo build.
#
# `TASK-0034` — product acceptance of bounded local search and "Ouvrir dans
# l'Explorateur" in the real WebView2 host. The tree is generated by
# `task0034-seed-proof.py` under the proof root and dies with it.
# **No personal folder is ever involved.**
#
# This run invokes `map_reveal_node` on a synthetic target, which spawns a
# real `explorer.exe` window. That window is not closed by this script —
# `TASK-0034` explicitly forbids killing Explorer globally — so it may
# remain open afterwards; that is expected, not a failure.
[CmdletBinding()]
param([int]$Port = 9334)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository
$variant = 'task0034-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null
$seed = python scripts/task0034-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic tree/catalogue preparation failed' }
$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'
$application = Start-Process -FilePath $executable -PassThru -WindowStyle Hidden -WorkingDirectory $repository -RedirectStandardOutput (Join-Path $proofRoot 'app.log') -RedirectStandardError (Join-Path $proofRoot 'app-error.log')
try {
    # The seed travels on stdin, not the command line, for the same reason as
    # TASK-0032/TASK-0033: the absolute path is a search key for the harness,
    # never a value it exposes.
    $seed | node scripts/task0034-webview2.mjs $Port $variant
    if ($LASTEXITCODE -ne 0) { throw "WebView2 proof failed; inspect .filetopo-sandbox/$variant" }
} finally {
    # Close only the process this script launched. No filesystem deletion,
    # and no attempt to close whatever Explorer window map_reveal_node opened.
    if (-not $application.HasExited) { $null = $application.CloseMainWindow() }
}
