# Run after pnpm build and cargo build.
#
# `TASK-0038` — product acceptance of the journal-derived seen/unseen state in
# the real WebView2 host. Both trees are generated by `task0038-seed-proof.py`
# under the proof root and die with it. **No personal folder is ever involved.**
#
# Two real launches of the same executable against the SAME sandbox variant
# (same brain indexes, so the acknowledgements genuinely persist):
#
#   phase 1  first index -> nothing unseen; create / modify / delete performed
#            on disk OUTSIDE the product process between real `Actualiser`
#            clicks; the seen/unseen state driven through the real panels
#            (mark a change, mark an element, « Tout marquer vu » with its
#            inline confirmation and a real cancel); a change AFTER mark-all;
#            then a second brain proving nothing is shared
#   (real close, real restart)
#   phase 2  the very same states, flag for flag, after the restart
[CmdletBinding()]
param([int]$Port = 9338)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository

$variant = 'task0038-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null

$seedJson = python scripts/task0038-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic tree/catalogue preparation failed' }

$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'

function Invoke-Phase {
    param([int]$Phase)
    Write-Host "TASK-0038: passe $Phase - demarrage reel de l'application"
    $application = Start-Process -FilePath $executable -PassThru -WindowStyle Hidden -WorkingDirectory $repository `
        -RedirectStandardOutput (Join-Path $proofRoot "app-phase$Phase.log") -RedirectStandardError (Join-Path $proofRoot "app-error-phase$Phase.log")
    try {
        # The seed travels on stdin, not the command line: the absolute paths
        # are search keys for the harness, never values it exposes.
        $seedJson | node scripts/task0038-webview2.mjs $Port $variant $Phase
        if ($LASTEXITCODE -ne 0) { throw "TASK-0038: WebView2 proof failed at phase $Phase; inspect $proofRoot" }
    } finally {
        # A REAL close: the window is asked first, the process only stopped if
        # it refuses — and it is the process this script just started.
        if (-not $application.HasExited) {
            $null = $application.CloseMainWindow()
            if (-not $application.WaitForExit(15000)) {
                Write-Host "TASK-0038: la fenetre n'a pas repondu, arret du processus demarre ici"
                Stop-Process -Id $application.Id -ErrorAction SilentlyContinue
            }
        }
        $application.WaitForExit()
    }
}

Invoke-Phase -Phase 1
Start-Sleep -Seconds 2
Invoke-Phase -Phase 2

$phase1 = Get-Content (Join-Path $proofRoot 'phase1.json') -Raw | ConvertFrom-Json
$phase2 = Get-Content (Join-Path $proofRoot 'phase2.json') -Raw | ConvertFrom-Json
$fatal1 = [int](Get-Content (Join-Path $proofRoot 'phase1-fatal-count.json') -Raw)
$fatal2 = [int](Get-Content (Join-Path $proofRoot 'phase2-fatal-count.json') -Raw)
$totalFatal = $fatal1 + $fatal2
if ($totalFatal -ne 0) {
    throw "TASK-0038: $totalFatal fatal console error(s) across the two phases"
}

# Only synthetic relative names, synthetic ids, counters and booleans.
$artifact = [ordered]@{
    task = 'TASK-0038'
    status = 'NONCANONICAL_ENGINEERING_EVIDENCE'
    engine = 'Windows Tauri / real WebView2'
    source = 'two REAL_ROOT brains registered internally (task0038-seed-proof.py) -> real fs create/modify/delete outside the process -> real Actualiser clicks -> real panels (Changements, details) -> map_change_mark_seen / map_node_mark_seen / map_change_mark_all_seen'
    realProcessRestarts = 1
    tree = [ordered]@{
        generatedByTheProofNotByTheUser = $true
        personalDataUsed               = $false
        brains                         = 2
    }
    schemaVersion                        = $phase1.schemaVersion
    baseline = [ordered]@{
        firstBuildNothingUnseen            = [bool]$phase1.firstBuildNothingUnseen
        markAllDisabledWhenNothingUnseen   = [bool]$phase1.markAllDisabledWhenNothingUnseen
    }
    create = [ordered]@{
        eventIsUnseen                      = [bool]$phase1.createEventUnseen
        nodeIsNewAndUnseen                 = [bool]$phase1.createNodeNewAndUnseen
        selectionDidNotMarkSeen            = [bool]$phase1.selectionDidNotMarkSeen
        markChangeMakesNodeNoLongerNew     = [bool]$phase1.markChangeNodeNoLongerNew
    }
    modify = [ordered]@{
        nodeUnseenButNotNew                = [bool]$phase1.modifyNodeUnseenNotNew
        markElementAcknowledgesIt          = [bool]$phase1.markElementSeen
    }
    markAll = [ordered]@{
        unseenBefore                       = $phase1.unseenBeforeMarkAll
        firstClickOpensConfirmationOnly    = [bool]$phase1.firstClickNoMutation
        cancelMutatesNothing               = [bool]$phase1.cancelNoMutation
        confirmMarksEverything             = [bool]$phase1.confirmMarksEverything
        deletedEventAcknowledgedAsChange   = [bool]$phase1.deletedAcknowledged
        changeAfterMarkAllStaysUnseen      = [bool]$phase1.changeAfterMarkAllUnseen
        nodeAfterMarkAllIsNew              = [bool]$phase1.nodeAfterMarkAllNew
    }
    secondBrain = [ordered]@{
        indexedIndependently               = [bool]$phase1.secondBrainBaseline
        itsOwnChangesAreUnseen             = [bool]$phase1.secondBrainUnseen
        firstBrainUntouchedBySecond        = [bool]$phase1.firstBrainUntouchedBySecond
        markingSecondLeavesFirstAlone      = [bool]$phase1.markingSecondLeavesFirstAlone
        switchingBackShowsFirstStateOnly   = [bool]$phase1.switchBackShowsFirstOnly
    }
    afterRealRestart = [ordered]@{
        firstBrainFlagsIdentical           = [bool]$phase2.firstBrainFlagsIdentical
        firstBrainUnseenTotal              = $phase2.firstBrainUnseenTotal
        secondBrainFlagsIdentical          = [bool]$phase2.secondBrainFlagsIdentical
        secondBrainUnseenTotal             = $phase2.secondBrainUnseenTotal
        newNodeStillNew                    = [bool]$phase2.newNodeStillNew
        acknowledgedNodeStillSeen          = [bool]$phase2.acknowledgedNodeStillSeen
        panelShowsPersistedState           = [bool]$phase2.panelShowsPersistedState
        openReadNoSource                   = [bool]$phase2.openAfterRestartReadNoSource
    }
    noAbsolutePathOrIdentityLeakPhase1   = [bool]$phase1.noAbsolutePathOrIdentityLeak
    noAbsolutePathOrIdentityLeakPhase2   = [bool]$phase2.noAbsolutePathOrIdentityLeak
    fatalConsoleErrors                   = $totalFatal
    limits = @(
        'No personal brain: both analysed trees were generated by task0038-seed-proof.py and die with the proof root',
        'Modification is driven by a size change (deterministic); a timestamp-only change is proved at the Rust level',
        'The journal date is the detection instant, never the instant the disk changed; this replay asserts states and identities, not wall-clock values',
        'Development workstation; not a modest-laptop acceptance test'
    )
}

$artifact | ConvertTo-Json -Depth 6 | Set-Content -Path (Join-Path $repository 'docs/performance/runs/TASK-0038-webview2.json')
Write-Output 'TASK-0038: real launches complete; artefact written to docs/performance/runs/TASK-0038-webview2.json'
