# Run after `pnpm build` and `pnpm tauri build --debug --no-bundle`.
#
# `TASK-0043` — product acceptance of the AUTOMATIC WATCHER (`F-030`, `DEC-0041`) in the
# real WebView2 host. The trees are generated by `task0043-seed-proof.py` under the proof
# root and die with it. **No personal folder is ever involved.**
#
# Two real launches of the same executable against the SAME sandbox variant, with a REAL
# close between them and the source changed while the application is closed:
#
#   phase 1  baseline (the one click on Actualiser) -> the watcher starts by itself ->
#            external changes appear in the map, the journal and the new / unseen filter
#            WITHOUT a click -> a burst of external operations converges -> the whole root
#            is moved away (DEGRADED / UNAVAILABLE, map kept, zero DELETED) -> the same
#            folder comes back (VERIFYING then WATCHING, SYNCED) -> a second brain is
#            isolated
#   (real close of the application; phase 0 changes the source while it is CLOSED)
#   phase 2  relaunch: no click, the Index equals the disk at the first stable state
#
# Cadences are shortened by the development-only overrides (never in a release build), so
# the proof does not wait five real seconds for each root-guard tick: FILETOPO_WATCH_*.
[CmdletBinding()]
param([int]$Port = 9343)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository

$variant = 'task0043-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null

$seedJson = python scripts/task0043-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic trees/catalogue preparation failed' }

$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:FILETOPO_WATCH_GUARD_MS = '500'
$env:FILETOPO_WATCH_COALESCE_MS = '150'
$env:FILETOPO_WATCH_CALM_MS = '150'
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'

function Stop-Application {
    param($Application)
    # A REAL close: the window is asked first, the process only stopped if it refuses — and
    # it is the process this script just started.
    if (-not $Application.HasExited) {
        $null = $Application.CloseMainWindow()
        if (-not $Application.WaitForExit(20000)) {
            Write-Host "TASK-0043: la fenetre n'a pas repondu, arret du processus demarre ici"
            Stop-Process -Id $Application.Id -ErrorAction SilentlyContinue
        }
    }
    $Application.WaitForExit()
}

function Invoke-Phase {
    param([int]$Phase)
    Write-Host "TASK-0043: passe $Phase - demarrage reel de l'application"
    $application = Start-Process -FilePath $executable -PassThru -WindowStyle Hidden -WorkingDirectory $repository `
        -RedirectStandardOutput (Join-Path $proofRoot "app-phase$Phase.log") -RedirectStandardError (Join-Path $proofRoot "app-error-phase$Phase.log")
    try {
        # The seed travels on stdin, not the command line: the absolute paths are search
        # keys for the harness, never values it exposes.
        $errorFile = Join-Path $proofRoot "harness-error-phase$Phase.txt"
        $seedJson | node scripts/task0043-webview2.mjs $Port $variant $Phase 2> $errorFile
        if ($LASTEXITCODE -ne 0) {
            Get-Content -LiteralPath $errorFile -ErrorAction SilentlyContinue | Select-Object -First 30 | ForEach-Object { Write-Host $_ }
            throw "TASK-0043: WebView2 proof failed at phase $Phase; inspect $proofRoot"
        }
    } finally {
        Stop-Application -Application $application
    }
}

Invoke-Phase -Phase 1
Start-Sleep -Seconds 2

# Phase 0 — the application is CLOSED; the source moves on.
Write-Host 'TASK-0043: application fermee - le harnais modifie la source'
$seedJson | node scripts/task0043-webview2.mjs $Port $variant 0
if ($LASTEXITCODE -ne 0) { throw 'TASK-0043: the offline mutation failed' }
Start-Sleep -Seconds 1

Invoke-Phase -Phase 2

$phase1 = Get-Content (Join-Path $proofRoot 'phase1.json') -Raw | ConvertFrom-Json
$phase2 = Get-Content (Join-Path $proofRoot 'phase2.json') -Raw | ConvertFrom-Json
$offline = Get-Content (Join-Path $proofRoot 'offline.json') -Raw | ConvertFrom-Json
$fatal1 = [int](Get-Content (Join-Path $proofRoot 'phase1-fatal-count.json') -Raw)
$fatal2 = [int](Get-Content (Join-Path $proofRoot 'phase2-fatal-count.json') -Raw)
$totalFatal = $fatal1 + $fatal2
if ($totalFatal -ne 0) {
    throw "TASK-0043: $totalFatal fatal console error(s) across the two phases"
}

# Only synthetic ids, counters, closed words and booleans.
$artifact = [ordered]@{
    task = 'TASK-0043'
    status = 'NONCANONICAL_ENGINEERING_EVIDENCE'
    engine = 'Windows Tauri / real WebView2'
    source = 'two REAL_ROOT brains registered internally (task0043-seed-proof.py); one click on Actualiser for the baseline, then every change is made by the harness on disk, outside the process, with NO click: external changes, a burst, the whole root moved away and put back, a second brain; then a REAL close, the source changed while the application is closed, a REAL relaunch with nobody clicking; the outcome of each IPC is read from the Tauri-Response header on the wire (CDP Network), every state from the real badges and panels, and every backend watcher event is recorded from the page and checked for the closed envelope'
    realProcessRestarts = 1
    developmentCadences = 'FILETOPO_WATCH_GUARD_MS=500, COALESCE_MS=150, CALM_MS=150 (development build only; the product defaults are 5 s / 300 ms / 300 ms)'
    tree = [ordered]@{
        generatedByTheProofNotByTheUser = $true
        personalDataUsed               = $false
        brains                         = 2
    }
    watcherStartsByItself = [ordered]@{
        startsWithoutAClick                  = [bool]$phase1.watcherStartsByItself
        badgeIsNativeAndTextual              = [bool]$phase1.watchingBadgeIsNativeAndTextual
        trail                                = @($phase1.startTrail)
    }
    externalChangesWithoutAClick = [ordered]@{
        appearInMapWithoutAClick             = [bool]$phase1.externalChangesAppearWithoutAClick
        journalHoldsTheFiveNatures           = [bool]$phase1.journalHoldsTheFiveNatures
        newUnseenFollow                      = [bool]$phase1.newUnseenFollow
        newFilterFollows                     = [bool]$phase1.newFilterFollows
        newFilterScreenAndBackendAgree       = [bool]$phase1.newFilterViaApiAgrees
    }
    burst = [ordered]@{
        convergesToTheDisk                   = [bool]$phase1.burstConvergesToTheDisk
        operations                           = [int]$phase1.burst.operations
        mutatedMs                            = [int]$phase1.burst.mutatedMs
        convergedMs                          = [int]$phase1.burst.convergedMs
    }
    wholeRootMovedAway = [ordered]@{
        watcherDegradedSourceUnavailable     = [bool]$phase1.absentRootIsUnavailableNotDeleted
        mapKeptIndexUntouchedZeroDeleted     = [bool]$phase1.mapKeptAndZeroDeleted
        returnIsVerifiedThenStable           = [bool]$phase1.returnIsVerifiedThenStable
        returnTrail                          = @($phase1.returnTrail)
    }
    secondBrain = [ordered]@{
        isolated                             = [bool]$phase1.secondBrainIsIsolated
        aChangeInAdoesNotMoveB               = [bool]$phase1.brainAChangeDoesNotMoveBrainB
    }
    afterRealCloseAndOfflineChanges = [ordered]@{
        offlineChangesMadeWhileClosed        = $true
        nobodyClickedAnything                = [bool]$phase2.noClickAfterRestart
        indexEqualsDiskAtTheFirstStableState = [bool]$phase2.indexEqualsDiskAtTheFirstStableState
        revisionAdvancedWhileClosed          = [bool]$phase2.revisionAdvancedWhileClosed
        offlineChangesAreJournalled          = [bool]$phase2.offlineChangesAreJournalled
        screenShowsTheCaughtUpMap            = [bool]$phase2.screenShowsTheCaughtUpMap
        secondBrainCaughtUpToo               = [bool]$phase2.secondBrainCaughtUp
        watcherKeepsWorkingLive              = [bool]$phase2.liveAfterRestart
        initialVerificationObservedLiveOnScreen = [bool]$phase2.initialVerificationObservedLive
        sampledTrail                         = @($phase2.sampledTrail)
        expectedNodesAtTheDisk               = [int]$offline.expectedNodesA
    }
    noPathOrIdentityLeakPhase1 = [bool]$phase1.noPathOrIdentityLeak
    noPathOrIdentityLeakPhase2 = [bool]$phase2.noPathOrIdentityLeak
    watcherEventsRecordedPhase1 = [int]$phase1.eventsRecorded
    watcherEventsRecordedPhase2 = [int]$phase2.eventsRecorded
    fatalConsoleErrors = $totalFatal
    limits = @(
        'No personal brain: the analysed trees were generated by task0043-seed-proof.py and die with the proof root',
        'Filesystem changes are made by the harness with Node, in-process to the harness and outside FileTopo; a real user editor may batch or delay notifications differently',
        'The relaunch races the page load: the initial verification of a few thousand entries can finish before the page attaches, so the ordering claim "the Index equals the disk before any stable state" is proved by the Rust engine test that captures the Index inside the notifier at the instant WATCHING is announced, and here by the state at the first WATCHING the page could see (initialVerificationObservedLiveOnScreen says whether the transition itself was seen)',
        'The 5 s / 30 s product cadences are not waited for here: the development overrides shorten the root guard and the coalescing windows; the periodic fallback is proved by the Rust engine (a backend that declares itself unsupported), not by this run, which uses the native mechanism',
        'The volume is a local NTFS disk of a development workstation: a network share, a FAT volume, a cloud-synced folder and USN are not exercised',
        'Development workstation; not a modest-laptop acceptance test'
    )
}

$artifact | ConvertTo-Json -Depth 6 | Set-Content -Path (Join-Path $repository 'docs/performance/runs/TASK-0043-webview2.json')
Write-Output 'TASK-0043: real launches complete; artefact written to docs/performance/runs/TASK-0043-webview2.json'
