# Run after pnpm build and cargo build.
#
# `TASK-0039` — product acceptance of the dynamic filters (`F-022 / P-09`) in the
# real WebView2 host. Both trees are generated by `task0039-seed-proof.py` under
# the proof root and die with it. **No personal folder is ever involved.**
#
# One real launch (the persistence of the filters across a restart is out of
# scope: `P-19`). Every filesystem change is made on disk OUTSIDE the product
# process; every UI action is a real mouse click or key event through CDP.
[CmdletBinding()]
param([int]$Port = 9339)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository

$variant = 'task0039-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null

$seedJson = python scripts/task0039-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic tree/catalogue preparation failed' }

$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'

Write-Host "TASK-0039: demarrage reel de l'application"
$application = Start-Process -FilePath $executable -PassThru -WindowStyle Hidden -WorkingDirectory $repository `
    -RedirectStandardOutput (Join-Path $proofRoot 'app.log') -RedirectStandardError (Join-Path $proofRoot 'app-error.log')
try {
    # The seed travels on stdin, not the command line: the absolute paths are
    # search keys for the harness, never values it exposes.
    $seedJson | node scripts/task0039-webview2.mjs $Port $variant
    if ($LASTEXITCODE -ne 0) { throw "TASK-0039: WebView2 proof failed; inspect $proofRoot" }
} finally {
    # A REAL close: the window is asked first, the process only stopped if it
    # refuses — and it is the process this script just started.
    if (-not $application.HasExited) {
        $null = $application.CloseMainWindow()
        if (-not $application.WaitForExit(15000)) {
            Write-Host "TASK-0039: la fenetre n'a pas repondu, arret du processus demarre ici"
            Stop-Process -Id $application.Id -ErrorAction SilentlyContinue
        }
    }
    $application.WaitForExit()
}

$run = Get-Content (Join-Path $proofRoot 'phase1.json') -Raw | ConvertFrom-Json
$fatal = [int](Get-Content (Join-Path $proofRoot 'phase1-fatal-count.json') -Raw)
if ($fatal -ne 0) { throw "TASK-0039: $fatal fatal console error(s)" }

# Only synthetic relative names, synthetic ids, counters and booleans.
$artifact = [ordered]@{
    task = 'TASK-0039'
    status = 'NONCANONICAL_ENGINEERING_EVIDENCE'
    engine = 'Windows Tauri / real WebView2'
    source = 'two REAL_ROOT brains registered internally (task0039-seed-proof.py) -> real fs create/modify outside the process -> real Actualiser clicks -> the real filter panel driven by real mouse clicks -> map_view with a filter'
    realProcessRestarts = 0
    tree = [ordered]@{
        generatedByTheProofNotByTheUser = $true
        personalDataUsed               = $false
        brains                         = 2
    }
    schemaVersion = $run.schemaVersion
    filters = [ordered]@{
        panelPresentAndInactiveAtStart     = [bool]$run.filterPanelPresentInactiveAtStart
        newShowsCreationsOnly              = [bool]$run.newShowsCreationsOnly
        unseenAddsTheModification          = [bool]$run.unseenAddsTheModification
        fileTypeExcludesFolders            = [bool]$run.fileTypeExcludesFolders
        localIsCoherentOnTheRealFixture    = [bool]$run.localIsCoherentOnTheRealFixture
        onlineOnlyEmptyOnLocalFixture      = [bool]$run.onlineOnlyEmptyOnLocalFixture
        canvasDrawsRolesInWords            = [bool]$run.canvasDrawsRolesInWords
    }
    seenState = [ordered]@{
        markSeenUpdatesCountAndProjection  = [bool]$run.markSeenUpdatesCountAndProjection
        markAllEmptiesUnseen               = [bool]$run.markAllEmptiesUnseen
    }
    reset = [ordered]@{
        resetRestoresTheNormalProjection   = [bool]$run.resetRestoresTheNormalProjection
    }
    pagination = [ordered]@{
        matches                            = 151
        pages                              = $run.paginationAcrossPages
        previousPageReplaces               = [bool]$run.previousPageReplaces
        actualiserKeepsAndRereadsTheFilter = [bool]$run.actualiserKeepsAndRereadsTheFilter
    }
    brainSwitchCarriesNoFilterNorCounter = [bool]$run.brainSwitchCarriesNoFilterNorCounter
    noAbsolutePathOrIdentityLeak         = [bool]$run.noAbsolutePathOrIdentityLeak
    fatalConsoleErrors                   = $fatal
    limits = @(
        'No personal brain: both analysed trees were generated by task0039-seed-proof.py and die with the proof root',
        'ONLINE_ONLY is proved at the Rust level; no Cloud Files placeholder is fabricated or hydrated: on this fixture the online-only filter is empty, which is the correct answer',
        'The filters are not persisted across a restart (P-19, out of scope): no restart is exercised',
        'Development workstation; not a modest-laptop acceptance test'
    )
}

$artifact | ConvertTo-Json -Depth 6 | Set-Content -Path (Join-Path $repository 'docs/performance/runs/TASK-0039-webview2.json')
Write-Output 'TASK-0039: real launch complete; artefact written to docs/performance/runs/TASK-0039-webview2.json'
