"""Fresh REAL_ROOT catalogue with TWO small real trees — TASK-0041.

`TASK-0041` proves that the manual `Actualiser` of an already-indexed brain goes
through the incremental kernel on a real Windows host: files and folders are
created, modified, deleted, renamed and moved **entirely outside the running
process**, between real `Actualiser` clicks, and the summary, the journal, the
NEW/UNSEEN filters and the seen state are then read through the real panels —
before and after a REAL process restart — on one brain, and checked to be
unaffected on a second one.

Two brains, each with its own tiny tree, because « second cerveau → aucun état
partagé » is a claim about two brains, not one. Nothing here is anybody's data:
both trees are generated by this script under the proof root and die with it.
The registration is written directly to a fresh sandbox variant's catalogue,
exactly as `task0038-seed-proof.py` established.
"""

import json
import sqlite3
import sys
import uuid
from pathlib import Path

repository = Path(__file__).resolve().parent.parent
variant = sys.argv[1]
assert variant.startswith("task0041-") and variant.replace("-", "").isalnum()

proof_root = repository / ".filetopo-sandbox" / variant
state_root = repository / ".filetopo-sandbox" / "variants" / variant

# Siblings of the FileTopo state space, never an ancestor or a descendant of it
# — `DEC-0033` G's containment rule. Named `t` and `u`, not something
# descriptive, to leave the path budget to what the proof actually needs.
first_root = proof_root / "t"
second_root = proof_root / "u"
first_root.mkdir(parents=True, exist_ok=False)
second_root.mkdir(parents=True, exist_ok=False)

written = 0


def touch(path: Path, content: str) -> None:
    global written
    path.write_text(content, encoding="utf-8")
    written += 1


# First brain: files the proof modifies, deletes, renames and moves, a folder
# with a nested folder the proof renames as a whole, and a few files that never
# change so an unchanged Actualiser is provably quiet.
touch(first_root / "a-modifier.txt", "synthetique — avant\n")
touch(first_root / "a-supprimer.txt", "synthetique — sera supprime\n")
for i in range(3):
    touch(first_root / f"stable-{i}.txt", f"synthetique stable {i}\n")
(first_root / "dossier" / "sous").mkdir(parents=True)
touch(first_root / "dossier" / "enfant.txt", "synthetique enfant\n")
touch(first_root / "dossier" / "sous" / "profond.txt", "synthetique profond\n")
(first_root / "vide").mkdir()

# Second brain: a base file only. Its changes are made by the proof.
touch(second_root / "base-b.txt", "synthetique — second cerveau\n")

brains = state_root / "brains"
brains.mkdir(parents=True, exist_ok=False)
first_brain = "real-" + str(uuid.uuid4())
second_brain = "real-" + str(uuid.uuid4())
with sqlite3.connect(brains / "catalog.sqlite") as db:
    db.execute(
        """CREATE TABLE brains (
             brain_id TEXT PRIMARY KEY CHECK(length(brain_id) > 0),
             display_name TEXT NOT NULL CHECK(length(trim(display_name)) > 0),
             color TEXT NOT NULL CHECK(length(color) = 7 AND substr(color, 1, 1) = '#'),
             icon TEXT NOT NULL CHECK(length(icon) > 0),
             source_kind TEXT NOT NULL CHECK(source_kind IN ('SYNTHETIC_FIXTURE', 'REAL_ROOT')),
             source_ref TEXT NOT NULL CHECK(length(source_ref) > 0),
             source_label TEXT NOT NULL CHECK(length(trim(source_label)) > 0),
             source_path BLOB,
             position INTEGER NOT NULL,
             CHECK ((source_kind = 'REAL_ROOT') = (source_path IS NOT NULL))
           )"""
    )
    db.execute("CREATE TABLE catalog_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)")
    for brain_id, name, color, icon, root, position in (
        (first_brain, "Arbre topographique de test", "#2F6DA8", "▣", first_root, 4),
        (second_brain, "Second arbre de test", "#A85F2F", "◆", second_root, 5),
    ):
        db.execute(
            "INSERT INTO brains VALUES (?,?,?,?,?,?,?,?,?)",
            (
                brain_id,
                name,
                color,
                icon,
                "REAL_ROOT",
                str(uuid.uuid4()),
                root.name,
                str(root.resolve()).encode("utf-16-le"),
                position,
            ),
        )
    db.execute("INSERT INTO catalog_meta VALUES ('active_brain_id', ?)", (first_brain,))
    db.execute("INSERT INTO catalog_meta VALUES ('schema_version', '2')")
    db.execute("PRAGMA user_version=2")

print(
    json.dumps(
        {
            "brainId": first_brain,
            "secondBrainId": second_brain,
            "absolutePath": str(first_root.resolve()),
            "secondAbsolutePath": str(second_root.resolve()),
            "entriesWritten": written,
        }
    )
)
