# Run after pnpm build and cargo build.
#
# `TASK-0041` — product acceptance of the manual Actualiser through the
# incremental kernel (`F-029` / `F-031`) in the real WebView2 host. Both trees are
# generated by `task0041-seed-proof.py` under the proof root and die with it.
# **No personal folder is ever involved.**
#
# Two real launches of the same executable against the SAME sandbox variant
# (same brain indexes, so the journal and the acknowledgements genuinely persist):
#
#   phase 1  first Actualiser (BASELINE_FULL) -> unchanged Actualiser
#            (INCREMENTAL, no-op, same revision) -> external create / modify /
#            delete / rename / move / new folder performed on disk OUTSIDE the
#            product process, then ONE real Actualiser (INCREMENTAL, exact
#            summary, one new revision) -> journal and NEW/UNSEEN filters through
#            the real panels -> mark all seen, a later change reappears -> a
#            folder renamed with its descendants -> Reconstruire
#            (EXPLICIT_REBUILD_FULL) -> incremental again -> a second brain
#   (real close, real restart)
#   phase 2  journal, seen state and revision identical; a cold Actualiser is
#            incremental and quiet; one more change is applied incrementally
[CmdletBinding()]
param([int]$Port = 9341)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository

$variant = 'task0041-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null

$seedJson = python scripts/task0041-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic tree/catalogue preparation failed' }

$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'

function Invoke-Phase {
    param([int]$Phase)
    Write-Host "TASK-0041: passe $Phase - demarrage reel de l'application"
    $application = Start-Process -FilePath $executable -PassThru -WindowStyle Hidden -WorkingDirectory $repository `
        -RedirectStandardOutput (Join-Path $proofRoot "app-phase$Phase.log") -RedirectStandardError (Join-Path $proofRoot "app-error-phase$Phase.log")
    try {
        # The seed travels on stdin, not the command line: the absolute paths
        # are search keys for the harness, never values it exposes.
        $errorFile = Join-Path $proofRoot "harness-error-phase$Phase.txt"
        $seedJson | node scripts/task0041-webview2.mjs $Port $variant $Phase 2> $errorFile
        if ($LASTEXITCODE -ne 0) {
            Get-Content -LiteralPath $errorFile -ErrorAction SilentlyContinue | Select-Object -First 30 | ForEach-Object { Write-Host $_ }
            throw "TASK-0041: WebView2 proof failed at phase $Phase; inspect $proofRoot"
        }
    } finally {
        # A REAL close: the window is asked first, the process only stopped if
        # it refuses — and it is the process this script just started.
        if (-not $application.HasExited) {
            $null = $application.CloseMainWindow()
            if (-not $application.WaitForExit(15000)) {
                Write-Host "TASK-0041: la fenetre n'a pas repondu, arret du processus demarre ici"
                Stop-Process -Id $application.Id -ErrorAction SilentlyContinue
            }
        }
        $application.WaitForExit()
    }
}

Invoke-Phase -Phase 1
Start-Sleep -Seconds 2
Invoke-Phase -Phase 2

$phase1 = Get-Content (Join-Path $proofRoot 'phase1.json') -Raw | ConvertFrom-Json
$phase2 = Get-Content (Join-Path $proofRoot 'phase2.json') -Raw | ConvertFrom-Json
$fatal1 = [int](Get-Content (Join-Path $proofRoot 'phase1-fatal-count.json') -Raw)
$fatal2 = [int](Get-Content (Join-Path $proofRoot 'phase2-fatal-count.json') -Raw)
$totalFatal = $fatal1 + $fatal2
if ($totalFatal -ne 0) {
    throw "TASK-0041: $totalFatal fatal console error(s) across the two phases"
}

# Only synthetic relative names, synthetic ids, counters and booleans.
$artifact = [ordered]@{
    task = 'TASK-0041'
    status = 'NONCANONICAL_ENGINEERING_EVIDENCE'
    engine = 'Windows Tauri / real WebView2'
    source = 'two REAL_ROOT brains registered internally (task0041-seed-proof.py) -> real fs create/modify/delete/rename/move outside the process -> real Actualiser / Reconstruire clicks -> map_refresh / map_rebuild round trips observed on the wire (CDP Network) -> mode, summary and revision read from the real panels that render those reports (summary, discreet mode label, Changements, filters, details)'
    realProcessRestarts = 1
    tree = [ordered]@{
        generatedByTheProofNotByTheUser = $true
        personalDataUsed               = $false
        brains                         = 2
    }
    schemaVersion = $phase1.schemaVersion
    applicationModes = [ordered]@{
        firstActualiserIsBaselineFull         = [bool]$phase1.firstIsBaselineFull
        firstInventsNoEvent                   = [bool]$phase1.firstInventsNoEvent
        unchangedActualiserIsIncrementalNoOp  = [bool]$phase1.unchangedIsIncrementalNoOp
        batchIsIncrementalWithExactSummary    = [bool]$phase1.batchIsIncrementalWithExactSummary
        reconstruireIsExplicitFull            = [bool]$phase1.rebuildIsExplicitFull
        incrementalAgainAfterRebuild          = [bool]$phase1.incrementalAgainAfterRebuild
    }
    incrementalResult = [ordered]@{
        identitiesKeptThroughRefresh          = [bool]$phase1.identitiesKeptThroughIncrementalRefresh
        journalMatchesTheBatch                = [bool]$phase1.journalMatchesTheBatch
        filtersExactAfterIncrementalRefresh   = [bool]$phase1.filtersExactAfterIncrementalRefresh
        changeAfterSeenReappears              = [bool]$phase1.changeAfterSeenReappears
        seenElementChangedAgainIsUnseen       = [bool]$phase1.seenElementChangedAgainIsUnseen
        folderRenameKeepsDescendants          = [bool]$phase1.folderRenameKeepsDescendants
        rebuildKeepsJournalAndSeenState       = [bool]$phase1.rebuildKeepsJournalAndSeenState
    }
    secondBrain = [ordered]@{
        baselineThenIncremental               = [bool]$phase1.secondBrainBaseline
        firstBrainQuietIncrementalBesideIt    = [bool]$phase1.firstBrainQuietIncrementalBesideSecond
        firstBrainUntouchedBySecond           = [bool]$phase1.firstBrainUntouchedBySecond
    }
    afterRealRestart = [ordered]@{
        journalAndSeenStateIdentical          = [bool]$phase2.journalAndSeenStateIdentical
        indexIdentityAndRevisionKept          = [bool]$phase2.indexIdentityAndRevisionKept
        coldRefreshIsIncrementalNoOp          = [bool]$phase2.coldRefreshIsIncrementalNoOp
        changeAfterRestartIsIncremental       = [bool]$phase2.changeAfterRestartIsIncremental
    }
    noAbsolutePathOrIdentityLeakPhase1   = [bool]$phase1.noAbsolutePathOrIdentityLeak
    noAbsolutePathOrIdentityLeakPhase2   = [bool]$phase2.noAbsolutePathOrIdentityLeak
    fatalConsoleErrors                   = $totalFatal
    limits = @(
        'No personal brain: both analysed trees were generated by task0041-seed-proof.py and die with the proof root',
        'The path that applied each scan is read from the discreet applicationMode label the real product renders from the real map_refresh / map_rebuild report (the body of a custom-protocol response is not retrievable through CDP, so the wire is used for completion and success only); the "never a full replacement" guard, SQL-failure rollback and root-identity refusal are proved at the Rust level (refresh_incremental_tests), not by breaking the real host',
        'Modification is driven by a size change (deterministic); a timestamp-only change is proved at the Rust level',
        'The scan stays complete on every Actualiser (F-029 manual, O(corpus)); nothing here measures scan cost or the watcher (F-030, out of scope)',
        'Development workstation; not a modest-laptop acceptance test'
    )
}

$artifact | ConvertTo-Json -Depth 6 | Set-Content -Path (Join-Path $repository 'docs/performance/runs/TASK-0041-webview2.json')
Write-Output 'TASK-0041: real launches complete; artefact written to docs/performance/runs/TASK-0041-webview2.json'
