# Run after pnpm build and cargo build; Vite must serve this checkout on port 1420.
#
# `TASK-0032` — the REAL_ROOT product path in the real host: a folder FileTopo
# did not create, an explicit indexing, an index-only reopen, a bounded map.
# The tree is generated by `task0032-seed-proof.py` under the proof root and
# dies with it. **No personal folder is ever involved.**
[CmdletBinding()]
param([int]$Port = 9332)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository
$variant = 'task0032-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null
$seed = python scripts/task0032-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'REAL_ROOT catalogue preparation failed' }
$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'
$application = Start-Process -FilePath $executable -PassThru -WindowStyle Hidden -WorkingDirectory $repository -RedirectStandardOutput (Join-Path $proofRoot 'app.log') -RedirectStandardError (Join-Path $proofRoot 'app-error.log')
try {
    # The seed travels on stdin, not on the command line: it carries the
    # absolute path the harness must hunt for in every DTO, and a command line
    # is visible to every process on the machine.
    $seed | node scripts/task0032-webview2.mjs $Port $variant
    if ($LASTEXITCODE -ne 0) { throw "WebView2 proof failed; inspect .filetopo-sandbox/$variant" }
} finally {
    # Close only the process this script launched. No filesystem deletion.
    if (-not $application.HasExited) { $null = $application.CloseMainWindow() }
}
