# Run after `pnpm build` and `pnpm tauri build --debug --no-bundle`.
#
# `TASK-0046` — product acceptance of the COMPLETE FR/EN RUNTIME (`DEC-0044`) in the real WebView2
# host. The two trees are generated by `task0046-seed-proof.py` under the proof root and die with
# it. **No personal folder is ever involved.**
#
# Two real launches of the same executable against the SAME sandbox variant AND the SAME WebView2
# profile, with a REAL close between them:
#
#   phase 1  a French host is simulated (`--lang=fr-CA`); a folder-backed brain and a built-in synthetic
#            brain are brought on screen through real interaction, every large surface is read in
#            French; the language is chosen ENGLISH by a real click; the document language follows;
#            every surface says its English label and no French is left; the names of the brains and
#            of the nodes are unchanged; the switch caused no backend command; the browser's storage
#            holds `filetopo.locale` and nothing else; the catalogue, the resume records, the Index,
#            the journal and the source are exactly what they were; moving to the other brain keeps
#            English
#   (real close of the application)
#   phase 2  relaunch: English is back BEFORE any interaction (although the host is still French);
#            the surfaces are opened again and say English; the language is switched to FRENCH by a
#            real click; the same surfaces say French, on both brains; again no command, no other
#            state moved
#
# The cadences of the watcher are shortened by the development-only overrides (never in a release
# build). The window is NOT hidden.
[CmdletBinding()]
param([int]$Port = 9346, [string]$HostLanguage = 'fr-CA')
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository

$variant = 'task0046-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null

$seedJson = python scripts/task0046-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic trees/catalogue preparation failed' }

$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:FILETOPO_WATCH_GUARD_MS = '500'
$env:FILETOPO_WATCH_COALESCE_MS = '150'
$env:FILETOPO_WATCH_CALM_MS = '150'
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --lang=$HostLanguage --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'

function Stop-Application {
    param($Application)
    # A REAL close: the window is asked first, the process only stopped if it refuses — and
    # it is the process this script just started.
    if (-not $Application.HasExited) {
        $null = $Application.CloseMainWindow()
        if (-not $Application.WaitForExit(20000)) {
            Write-Host "TASK-0046: la fenetre n'a pas repondu, arret du processus demarre ici"
            Stop-Process -Id $Application.Id -ErrorAction SilentlyContinue
        }
    }
    $Application.WaitForExit()
}

function Invoke-Phase {
    param([int]$Phase)
    Write-Host "TASK-0046: passe $Phase - demarrage reel de l'application"
    $application = Start-Process -FilePath $executable -PassThru -WorkingDirectory $repository `
        -RedirectStandardOutput (Join-Path $proofRoot "app-phase$Phase.log") -RedirectStandardError (Join-Path $proofRoot "app-error-phase$Phase.log")
    try {
        # The seed travels on stdin, not the command line: the absolute paths are search keys for
        # the harness, never values it exposes.
        $errorFile = Join-Path $proofRoot "harness-error-phase$Phase.txt"
        $seedJson | node scripts/task0046-webview2.mjs $Port $variant $Phase 2> $errorFile
        if ($LASTEXITCODE -ne 0) {
            Get-Content -LiteralPath $errorFile -ErrorAction SilentlyContinue | Select-Object -First 40 | ForEach-Object { Write-Host $_ }
            throw "TASK-0046: WebView2 proof failed at phase $Phase; inspect $proofRoot"
        }
    } finally {
        Stop-Application -Application $application
    }
}

Invoke-Phase -Phase 1
Start-Sleep -Seconds 2
Invoke-Phase -Phase 2

$phase1 = Get-Content (Join-Path $proofRoot 'phase1.json') -Raw | ConvertFrom-Json
$phase2 = Get-Content (Join-Path $proofRoot 'phase2.json') -Raw | ConvertFrom-Json
$fatal = 0
foreach ($n in 1, 2) { $fatal += [int](Get-Content (Join-Path $proofRoot "phase$n-fatal-count.json") -Raw) }
if ($fatal -ne 0) { throw "TASK-0046: $fatal fatal console error(s) across the two phases" }

$artifact = [ordered]@{
    task = 'TASK-0046'
    status = 'NONCANONICAL_ENGINEERING_EVIDENCE'
    engine = 'Windows Tauri / real WebView2'
    source = 'two REAL_ROOT brains registered internally (task0046-seed-proof.py), generated under the proof root and dying with it: no personal data. Mouse events are dispatched through the browser input pipeline (CDP Input.dispatchMouseEvent / Input.dispatchKeyEvent). Every logical value is read back from the real screen (text nodes and accessible names), from the catalogue (map_brains, map_brain_resume_state), from the Index and journal, from a SHA-256 of both trees, and from the browser''s storage; the product''s own IPC calls are read from the wire (CDP Network). One REAL close of the process; the SAME WebView2 profile is reused.'
    hostLanguageSimulated = $HostLanguage
    realProcessRestarts = 1
    tree = [ordered]@{
        generatedByTheProofNotByTheUser = $true
        personalDataUsed = $false
        brains = '2 folder-backed (Arbre Alix, Arbre Basile) + the built-in synthetic brains of the catalogue (Cerveau Alpha, Cerveau Beta, Cerveau Gamma)'
        brainNamesAreFrenchOnPurpose = 'a brain''s name is user data and is never translated; the synthetic fixture quasi-empty holds French-looking file names for the same reason'
    }
    phase1 = [ordered]@{
        hostLanguageAsSeenByThePage = $phase1.host
        atStart = $phase1.atStart
        surfacesInFrenchBeforeTheChoice = [ordered]@{
            folderBackedBrain = $phase1.frenchBeforeTheChoiceR
            syntheticBrain = $phase1.frenchBeforeTheChoiceS
        }
        choiceEnglish = $phase1.choiceEnglish
        surfacesInEnglishAfterTheChoice = [ordered]@{
            syntheticBrainOnScreenAtTheSwitch = $phase1.englishAfterTheChoiceS
            folderBackedBrainAfterMovingToIt = $phase1.englishAfterMovingToTheOtherBrainR
        }
        storageAtClose = $phase1.storageAtClose
    }
    afterTheRealClose = [ordered]@{
        hostLanguageAsSeenByThePage = $phase2.host
        atRelaunch = $phase2.atRelaunch
        selectionAfterRelaunch = $phase2.selectionAfterRelaunch
        surfacesInEnglishAfterRelaunch = [ordered]@{ folderBackedBrain = $phase2.englishAfterRelaunchR }
        choiceFrench = $phase2.choiceFrench
        surfacesInFrenchAfterTheChoice = [ordered]@{
            folderBackedBrainOnScreenAtTheSwitch = $phase2.frenchAfterTheChoiceR
            syntheticBrainAfterMovingToIt = $phase2.frenchAfterTheChoiceS
        }
        storageAtEnd = $phase2.storageAtEnd
    }
    checkedAroundEverySwitch = @(
        'the switch is a real click on a native button; the harness makes no call of its own during the window, so every map_* command seen on the wire in it would be the product''s: there is none',
        'document.documentElement.lang follows the choice and aria-pressed says which button holds',
        'the browser''s storage holds exactly one key, filetopo.locale, with the chosen value; sessionStorage is empty',
        'the catalogue (every brain record, the active brain), the resume records, the Index revisions and node counts, the journal totals and the unseen total are equal before and after',
        'the SHA-256 of every file and directory under both roots is equal before and after (and the source was never asked to be read again)',
        'the selection, the brain shown and the counts on the map are equal before and after',
        'the brain names and the node names are shown exactly as often as before, in their own words',
        'in English, no French accent or word is left in any text node or accessible name (names of brains and nodes excepted)'
    )
    fatalConsoleErrors = $fatal
    limits = @(
        'No personal brain: the analysed trees were generated by task0046-seed-proof.py and die with the proof root',
        'The host language is simulated with --lang on the WebView2 process; the value the page actually saw is published above (hostLanguageAsSeenByThePage)',
        'Mouse and key events are dispatched through the browser input pipeline by the harness (CDP), not through the operating system',
        'The close is a normal one (the window is asked to close); no claim about a crash of the process',
        'The native window title stays "FileTopo" in both languages: it is not a runtime string of the page',
        'Backend diagnostics (raw error text) may follow a localized message as a secondary detail (DEC-0044 section 7); none appeared during this run',
        'F-036 / WCAG 2.2 AA is not claimed; P-19 and P-21 stay partial; this is the language portion only',
        'Development workstation, local NTFS disk; not a modest-laptop acceptance test'
    )
}

$artifact | ConvertTo-Json -Depth 10 | Set-Content -Path (Join-Path $repository 'docs/performance/runs/TASK-0046-webview2.json') -Encoding utf8
Write-Output 'TASK-0046: real launches complete; artefact written to docs/performance/runs/TASK-0046-webview2.json'
