# Run after pnpm build and cargo build.
#
# `TASK-0036` — product acceptance of `DEC-0009` I-E stable node identity in
# the real WebView2 host. The tree is generated by `task0036-seed-proof.py`
# under the proof root and dies with it. **No personal folder is ever
# involved.**
#
# A single real launch is enough: unlike `TASK-0035` A's preference, node
# identity does not need to survive a process restart — it needs to survive
# a republish. `task0036-webview2.mjs` renames, moves and finally
# deletes/creates real files on disk, **between** real `Actualiser` clicks
# of the SAME running session, and verifies the product's own `nodeId`
# never moves for the same object and never gets reused for a different one.
#
# This run also invokes `map_reveal_node` on a synthetic target, which spawns
# a real `explorer.exe` window. That window is not closed by this script —
# `TASK-0034`/`TASK-0035` explicitly forbid killing Explorer globally — so it
# may remain open afterwards; that is expected, not a failure.
[CmdletBinding()]
param([int]$Port = 9336)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository

$variant = 'task0036-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null

$seed = python scripts/task0036-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic tree/catalogue preparation failed' }

$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'

$application = Start-Process -FilePath $executable -PassThru -WindowStyle Hidden -WorkingDirectory $repository `
    -RedirectStandardOutput (Join-Path $proofRoot 'app.log') -RedirectStandardError (Join-Path $proofRoot 'app-error.log')
try {
    # The seed travels on stdin, not the command line, for the same reason as
    # TASK-0032..0035: the absolute path is a search key for the harness,
    # never a value it exposes. The renames/moves themselves are performed by
    # the Node script directly, on this same absolute path, entirely outside
    # the product process.
    $seed | node scripts/task0036-webview2.mjs $Port $variant
    if ($LASTEXITCODE -ne 0) { throw "TASK-0036: WebView2 proof failed; inspect $proofRoot" }
} finally {
    # A REAL close: the window is asked first, the process only stopped if it
    # refuses — and it is the process this script just started.
    if (-not $application.HasExited) {
        $null = $application.CloseMainWindow()
        if (-not $application.WaitForExit(15000)) {
            Write-Host "TASK-0036: la fenetre n'a pas repondu, arret du processus demarre ici"
            Stop-Process -Id $application.Id -ErrorAction SilentlyContinue
        }
    }
    $application.WaitForExit()
}

$result = Get-Content (Join-Path $proofRoot 'result.json') -Raw | ConvertFrom-Json
$fatal = [int](Get-Content (Join-Path $proofRoot 'fatal-count.json') -Raw)

$artifact = [ordered]@{
    task = 'TASK-0036'
    status = 'NONCANONICAL_ENGINEERING_EVIDENCE'
    engine = 'Windows Tauri / real WebView2'
    source = 'REAL_ROOT registered internally (task0036-seed-proof.py) -> real fs rename/move/delete -> map_refresh -> map_resolve_node/map_node_detail'
    realProcessRestarts = 0
    tree = [ordered]@{
        generatedByTheProofNotByTheUser = $true
        personalDataUsed               = $false
        indexedNodeCount               = $result.indexedNodeCount
    }
    nodeIdIdenticalAfterRename       = [bool]$result.nodeIdIdenticalAfterRename
    oldPathGoneAfterRename           = [bool]$result.oldPathGoneAfterRename
    nodeIdIdenticalAfterMove         = [bool]$result.nodeIdIdenticalAfterMove
    movedParentIsDestinationFolder   = [bool]$result.movedParentIsDestinationFolder
    movedFolderKeepsItsOwnId         = [bool]$result.movedFolderKeepsItsOwnId
    movedFoldersChildKeepsItsId      = [bool]$result.movedFoldersChildKeepsItsId
    movedChildParentIsMovedFolder    = [bool]$result.movedChildParentIsMovedFolder
    newObjectNeverRecyclesADeletedId = [bool]$result.newObjectNeverRecyclesADeletedId
    searchStillFinds                 = [bool]$result.searchStillFinds
    childrenStillPage                = [bool]$result.childrenStillPage
    projectionStillRenders           = [bool]$result.projectionStillRenders
    revealStillSucceeds              = [bool]$result.revealStillSucceeds
    copyStillSucceeds                = [bool]$result.copyStillSucceeds
    copyFailureReason                = $result.copyFailureReason
    noAbsolutePathOrStableKeyLeak    = [bool]$result.noAbsolutePathOrStableKeyLeak
    fatalConsoleErrors               = $fatal
    limits = @(
        'No personal brain: the analysed tree was generated by task0036-seed-proof.py and dies with the proof root',
        'seen persistence across a SYSTEM rename/move is proved on real Windows at the Rust integration level (src-tauri/src/map/stable_identity_tests.rs), not replayed through this WebView2 script: the product exposes no seen UI/command to drive it from the page, and reactivating the retired 0.1 command was out of scope',
        'map_reveal_node was invoked directly rather than also through a UI click, to avoid spawning a second visible Explorer window for the same fact — the same convention TASK-0034/0035 established',
        'map_copy_node_path writes straight to the OS clipboard and returns no value; this replay checks it succeeds, not the clipboard byte-for-byte (TASK-0035 C already proves that)',
        'Development workstation; not a modest-laptop acceptance test',
        'A real explorer.exe window may remain open after this run — TASK-0034/0035/0036 forbid killing it globally, so it is left for Windows to manage'
    )
}

$artifact | ConvertTo-Json -Depth 6 | Set-Content -Path (Join-Path $repository 'docs/performance/runs/TASK-0036-webview2.json')
Write-Output 'TASK-0036: real launch complete; artefact written to docs/performance/runs/TASK-0036-webview2.json'
