# Run after `pnpm build` and `pnpm tauri build --debug --no-bundle`.
#
# `TASK-0047` — accessibility closure of the REAL runtime (`DEC-0045`), in the real WebView2 host.
# The two trees are generated by `task0047-seed-proof.py` under the proof root and die with it.
# **No personal folder is ever involved.**
#
# One real launch. The harness (`task0047-webview2.mjs`) injects the `axe-core` installed in
# `node_modules` (a devDependency, never bundled) into the page, and:
#
#   -Mode baseline   audits every state of the matrix BEFORE any correction and publishes what axe
#                    finds (violations + incomplete) without judging it;
#   -Mode final      audits the same matrix, then walks the page with real keyboard events, measures
#                    focus visibility, contrast, non-colour alternatives, reduced motion and the
#                    invariants, and FAILS on anything unjustified.
#
# The host language is French (`--lang=fr-CA`, simulated as in TASK-0046); English is chosen by a real
# click. The colour scheme and `prefers-reduced-motion` are emulated in the real engine
# (CDP Emulation.setEmulatedMedia). The window is NOT hidden.
[CmdletBinding()]
param(
    [int]$Port = 9347,
    [ValidateSet('baseline', 'final')][string]$Mode = 'final',
    [string]$HostLanguage = 'fr-CA'
)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository

$variant = 'task0047-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null

$seedJson = python scripts/task0047-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic trees/catalogue preparation failed' }

$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:FILETOPO_WATCH_GUARD_MS = '500'
$env:FILETOPO_WATCH_COALESCE_MS = '150'
$env:FILETOPO_WATCH_CALM_MS = '150'
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --lang=$HostLanguage --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'
$artifact = if ($Mode -eq 'baseline') { 'docs/performance/runs/TASK-0047-baseline-webview2.json' } else { 'docs/performance/runs/TASK-0047-webview2.json' }

Write-Host "TASK-0047: mode $Mode - demarrage reel de l'application"
$application = Start-Process -FilePath $executable -PassThru -WorkingDirectory $repository `
    -RedirectStandardOutput (Join-Path $proofRoot 'app.log') -RedirectStandardError (Join-Path $proofRoot 'app-error.log')
try {
    # The seed travels on stdin, not the command line: the absolute paths are search keys for the
    # harness, never values it exposes.
    $errorFile = Join-Path $proofRoot 'harness-error.txt'
    $seedJson | node scripts/task0047-webview2.mjs $Port $variant $Mode $artifact 2> $errorFile
    if ($LASTEXITCODE -ne 0) {
        Get-Content -LiteralPath $errorFile -ErrorAction SilentlyContinue | Select-Object -First 60 | ForEach-Object { Write-Host $_ }
        throw "TASK-0047: WebView2 proof failed (mode $Mode); inspect $proofRoot"
    }
} finally {
    # A REAL close: the window is asked first, the process only stopped if it refuses — and it is
    # the process this script just started.
    if (-not $application.HasExited) {
        $null = $application.CloseMainWindow()
        if (-not $application.WaitForExit(20000)) {
            Write-Host "TASK-0047: la fenetre n'a pas repondu, arret du processus demarre ici"
            Stop-Process -Id $application.Id -ErrorAction SilentlyContinue
        }
    }
    $application.WaitForExit()
}
Write-Output "TASK-0047: real launch complete; artefact written to $artifact"
