# Run after pnpm build and cargo build.
#
# `TASK-0037` — product acceptance of the persistent change journal in the
# real WebView2 host. The tree is generated by `task0037-seed-proof.py` under
# the proof root (plus a 130-file batch the Node script writes) and dies with
# it. **No personal folder is ever involved.**
#
# Two real launches of the same executable against the SAME sandbox variant
# (same brain index, so the journal genuinely persists):
#
#   phase 1  first index -> empty journal; create / modify / rename / move /
#            delete performed on disk OUTSIDE the product process between real
#            `Actualiser` clicks, with exact counters and the same nodeId at
#            each step; a 130-file batch, filters and pagination through the
#            real panel
#   (real close, real restart)
#   phase 2  the same history, page for page, after the restart
[CmdletBinding()]
param([int]$Port = 9337)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository

$variant = 'task0037-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null

$seedJson = python scripts/task0037-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic tree/catalogue preparation failed' }

$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'

function Invoke-Phase {
    param([int]$Phase)
    Write-Host "TASK-0037: passe $Phase - demarrage reel de l'application"
    $application = Start-Process -FilePath $executable -PassThru -WindowStyle Hidden -WorkingDirectory $repository `
        -RedirectStandardOutput (Join-Path $proofRoot "app-phase$Phase.log") -RedirectStandardError (Join-Path $proofRoot "app-error-phase$Phase.log")
    try {
        # The seed travels on stdin, not the command line: the absolute path
        # is a search key for the harness, never a value it exposes.
        $seedJson | node scripts/task0037-webview2.mjs $Port $variant $Phase
        if ($LASTEXITCODE -ne 0) { throw "TASK-0037: WebView2 proof failed at phase $Phase; inspect $proofRoot" }
    } finally {
        # A REAL close: the window is asked first, the process only stopped if
        # it refuses — and it is the process this script just started.
        if (-not $application.HasExited) {
            $null = $application.CloseMainWindow()
            if (-not $application.WaitForExit(15000)) {
                Write-Host "TASK-0037: la fenetre n'a pas repondu, arret du processus demarre ici"
                Stop-Process -Id $application.Id -ErrorAction SilentlyContinue
            }
        }
        $application.WaitForExit()
    }
}

Invoke-Phase -Phase 1
Start-Sleep -Seconds 2
Invoke-Phase -Phase 2

$phase1 = Get-Content (Join-Path $proofRoot 'phase1.json') -Raw | ConvertFrom-Json
$phase2 = Get-Content (Join-Path $proofRoot 'phase2.json') -Raw | ConvertFrom-Json
$fatal1 = [int](Get-Content (Join-Path $proofRoot 'phase1-fatal-count.json') -Raw)
$fatal2 = [int](Get-Content (Join-Path $proofRoot 'phase2-fatal-count.json') -Raw)
$totalFatal = $fatal1 + $fatal2
if ($totalFatal -ne 0) {
    throw "TASK-0037: $totalFatal fatal console error(s) across the two phases"
}

# Only synthetic relative names, synthetic ids, counters and booleans.
$artifact = [ordered]@{
    task = 'TASK-0037'
    status = 'NONCANONICAL_ENGINEERING_EVIDENCE'
    engine = 'Windows Tauri / real WebView2'
    source = 'REAL_ROOT registered internally (task0037-seed-proof.py) -> real fs create/modify/rename/move/delete outside the process -> real Actualiser clicks -> map_change_journal -> ChangeJournalPanel'
    realProcessRestarts = 1
    tree = [ordered]@{
        generatedByTheProofNotByTheUser = $true
        personalDataUsed               = $false
        indexedNodeCount               = $phase1.indexedNodeCount
        syntheticBatchFiles            = 130
    }
    schemaVersion                        = $phase1.schemaVersion
    firstBuildBaseline                   = [bool]$phase1.firstBuildBaseline
    firstBuildJournalEmpty               = [bool]$phase1.firstBuildJournalEmpty
    unchangedRefreshZeroEvents           = [bool]$phase1.unchangedRefreshZeroEvents
    counters = [ordered]@{
        create   = 'created=1 total=1'
        modify   = 'modified=1 total=1'
        rename   = 'renamed=1 total=1'
        move     = 'moved=1 total=1'
        delete   = 'deleted=1 total=1'
        batch    = $phase1.batchCounters
    }
    createdEvent                         = [bool]$phase1.createdEvent
    modifiedEvent                        = [bool]$phase1.modifiedEvent
    renameKeepsNodeId                    = [bool]$phase1.renameKeepsNodeId
    renamedEvent                         = [bool]$phase1.renamedEvent
    moveKeepsNodeId                      = [bool]$phase1.moveKeepsNodeId
    movedEvent                           = [bool]$phase1.movedEvent
    deletedEvent                         = [bool]$phase1.deletedEvent
    deletedOffersNoSelection             = [bool]$phase1.deletedOffersNoSelection
    paginationPageSizes                  = $phase1.paginationPageSizes
    paginationNoGapNoDuplicate           = [bool]$phase1.paginationNoGapNoDuplicate
    pageBackRestoresFirstPage            = [bool]$phase1.pageBackRestoresFirstPage
    filterTotals = [ordered]@{
        created      = $phase1.filterCreatedTotal
        renamedMoved = $phase1.filterRenamedMovedTotal
        deleted      = $phase1.filterDeletedTotal
        modified     = $phase1.filterModifiedTotal
    }
    filtersRevocable                     = [bool]$phase1.filtersRevocable
    selectFromJournalShowsTheNode        = [bool]$phase1.selectFromJournalShowsTheNode
    apiPageIsBounded                     = [bool]$phase1.apiPageIsBounded
    apiCursorContinues                   = [bool]$phase1.apiCursorContinues
    afterRealRestart = [ordered]@{
        historyTotalSurvives                   = [bool]$phase2.historyTotalSurvives
        historyTotal                           = $phase2.historyTotalAfterRestart
        firstPageIdentical                     = [bool]$phase2.firstPageIdenticalAfterRestart
        lastPageIdentical                      = [bool]$phase2.lastPageIdenticalAfterRestart
        paginationNoGapNoDuplicate             = [bool]$phase2.paginationNoGapNoDuplicateAfterRestart
        allFiveNaturesSurvive                  = [bool]$phase2.allFiveNaturesSurvive
        deletedStillHistoryOnly                = [bool]$phase2.deletedStillHistoryOnly
        openReadNoSource                       = [bool]$phase2.openAfterRestartReadNoSource
    }
    noAbsolutePathOrIdentityLeakPhase1   = [bool]$phase1.noAbsolutePathOrIdentityLeak
    noAbsolutePathOrIdentityLeakPhase2   = [bool]$phase2.noAbsolutePathOrIdentityLeak
    fatalConsoleErrors                   = $totalFatal
    limits = @(
        'No personal brain: the analysed tree was generated by task0037-seed-proof.py and dies with the proof root',
        'Modification is driven by a size change (deterministic); a timestamp-only change is proved at the Rust level',
        'The journal date is the detection instant, never the instant the disk changed; this replay asserts counters and identities, not wall-clock values',
        'Development workstation; not a modest-laptop acceptance test'
    )
}

$artifact | ConvertTo-Json -Depth 6 | Set-Content -Path (Join-Path $repository 'docs/performance/runs/TASK-0037-webview2.json')
Write-Output 'TASK-0037: real launches complete; artefact written to docs/performance/runs/TASK-0037-webview2.json'
