"""Fresh REAL_ROOT catalogue and a small real tree — TASK-0036.

`TASK-0036` proves stable node identity on a real Windows host: a file is
renamed, then moved, **entirely outside the running process**, between two
real `Actualiser` clicks of the same product session. The tree therefore has
to be small and entirely under this script's control on disk — the opposite
of `TASK-0034`/`TASK-0035`'s thousands-of-files trees, which exist to
exercise pagination, not identity.

Nothing here is anybody's data; the tree is generated by this script under
the proof root and dies with it. The registration is written directly to a
fresh sandbox variant's catalogue, exactly as `task0032-seed-proof.py`
established.
"""

import json
import sqlite3
import sys
import uuid
from pathlib import Path

repository = Path(__file__).resolve().parent.parent
variant = sys.argv[1]
assert variant.startswith("task0036-") and variant.replace("-", "").isalnum()

proof_root = repository / ".filetopo-sandbox" / variant
state_root = repository / ".filetopo-sandbox" / "variants" / variant

# A sibling of the FileTopo state space, never an ancestor or a descendant of
# it — `DEC-0033` G's containment rule. Named `t`, not something descriptive,
# to leave the path budget to the depth this proof actually needs.
source_root = proof_root / "t"
source_root.mkdir(parents=True, exist_ok=False)

count = 0


def touch(path: Path, content: str) -> None:
    global count
    path.write_text(content, encoding="utf-8")
    count += 1


def mkdir(path: Path) -> None:
    global count
    path.mkdir(parents=True, exist_ok=False)
    count += 1


# The file whose identity travels through a rename, then a move.
touch(source_root / "avant.txt", "synthetique — identite stable\n")

# The destination folder the renamed file will be moved into. Not empty, so
# the move is proven amid real siblings rather than into an empty directory.
mkdir(source_root / "dossier")
touch(source_root / "dossier" / "existant.txt", "synthetique — deja present\n")

# A folder that itself gets moved, with a child, so the parent/child
# consistency of a moved subtree is provable too.
mkdir(source_root / "sous-arbre")
touch(source_root / "sous-arbre" / "enfant.txt", "synthetique — enfant deplace\n")
mkdir(source_root / "ailleurs")

# A file deleted and replaced by an unrelated one, so a fresh id (never
# recycled) is observable too.
touch(source_root / "a-supprimer.txt", "synthetique — sera supprime\n")

# A few loose files, so the tree is not suspiciously minimal.
for i in range(3):
    touch(source_root / f"r{i}.txt", f"synthetique racine {i}\n")

canonical = source_root.resolve()

brains = state_root / "brains"
brains.mkdir(parents=True, exist_ok=False)
brain_id = "real-" + str(uuid.uuid4())
source_ref = str(uuid.uuid4())
with sqlite3.connect(brains / "catalog.sqlite") as db:
    db.execute(
        """CREATE TABLE brains (
             brain_id TEXT PRIMARY KEY CHECK(length(brain_id) > 0),
             display_name TEXT NOT NULL CHECK(length(trim(display_name)) > 0),
             color TEXT NOT NULL CHECK(length(color) = 7 AND substr(color, 1, 1) = '#'),
             icon TEXT NOT NULL CHECK(length(icon) > 0),
             source_kind TEXT NOT NULL CHECK(source_kind IN ('SYNTHETIC_FIXTURE', 'REAL_ROOT')),
             source_ref TEXT NOT NULL CHECK(length(source_ref) > 0),
             source_label TEXT NOT NULL CHECK(length(source_label) > 0),
             source_path BLOB,
             position INTEGER NOT NULL,
             CHECK ((source_kind = 'REAL_ROOT') = (source_path IS NOT NULL))
           )"""
    )
    db.execute("CREATE TABLE catalog_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)")
    db.execute(
        "INSERT INTO brains VALUES (?,?,?,?,?,?,?,?,?)",
        (
            brain_id,
            "Arbre topographique de test",
            "#2F6DA8",
            "▣",
            "REAL_ROOT",
            source_ref,
            source_root.name,
            str(canonical).encode("utf-16-le"),
            4,
        ),
    )
    db.execute("INSERT INTO catalog_meta VALUES ('active_brain_id', ?)", (brain_id,))
    db.execute("INSERT INTO catalog_meta VALUES ('schema_version', '2')")
    db.execute("PRAGMA user_version=2")

print(
    json.dumps(
        {
            "brainId": brain_id,
            "sourceRef": source_ref,
            "sourceLabel": source_root.name,
            "absolutePath": str(canonical),
            "entriesWritten": count,
        }
    )
)
