# Run after pnpm build and cargo build.
#
# `TASK-0035` — product acceptance of the context panel, exact/paginated
# direct children and safe "Copier le chemin" in the real WebView2 host.
# The tree is generated by `task0035-seed-proof.py` under the proof root
# and dies with it. **No personal folder is ever involved.**
#
# Unlike TASK-0034's single-launch replay, `TASK-0035` A requires the
# details-panel preference to survive a REAL process exit and restart —
# something no page can fake from the inside. This script performs THREE
# real launches of the same executable against the SAME sandbox variant
# (same `catalog.sqlite`, so the preference genuinely persists):
#
#   phase 1  fresh profile: panel visible by default, children pagination,
#            a child outside the ordinary projection, reveal, copy, then
#            Masquer les détails
#   (real close, real restart)
#   phase 2  still hidden after the restart; Afficher les détails
#   (real close, real restart)
#   phase 3  still visible after the second restart
#
# The clipboard comparison for "Copier le chemin" happens in THIS script,
# right after phase 1 closes — the same OS-level clipboard the app's own
# `tauri-plugin-clipboard-manager` call just wrote to — and only the
# boolean match is kept in the published artefact, never the path itself.
#
# This run also invokes `map_reveal_node` on a synthetic target, which
# spawns a real `explorer.exe` window. That window is not closed by this
# script — `TASK-0034`/`TASK-0035` explicitly forbid killing Explorer
# globally — so it may remain open afterwards; that is expected, not a
# failure.
[CmdletBinding()]
param([int]$Port = 9335)
$ErrorActionPreference = 'Stop'
$repository = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $repository

$variant = 'task0035-' + [guid]::NewGuid().ToString('N')
$proofRoot = Join-Path $repository ".filetopo-sandbox/$variant"
New-Item -ItemType Directory -Path $proofRoot | Out-Null

$seedJson = python scripts/task0035-seed-proof.py $variant
if ($LASTEXITCODE -ne 0) { throw 'synthetic tree/catalogue preparation failed' }
$seed = $seedJson | ConvertFrom-Json

$env:FILETOPO_SANDBOX_VARIANT = $variant
$env:WEBVIEW2_USER_DATA_FOLDER = Join-Path $proofRoot 'webview-profile'
$env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$Port --disable-background-timer-throttling --disable-renderer-backgrounding --disable-backgrounding-occluded-windows"
$env:TEMP = Join-Path $proofRoot 'tmp'
$env:TMP = $env:TEMP
New-Item -ItemType Directory -Path $env:TEMP | Out-Null
$executable = Join-Path $repository 'src-tauri/target/debug/filetopo.exe'

function Invoke-Phase {
    param([int]$Phase)
    Write-Host "TASK-0035: passe $Phase — demarrage reel de l'application"
    $application = Start-Process -FilePath $executable -PassThru -WindowStyle Hidden -WorkingDirectory $repository `
        -RedirectStandardOutput (Join-Path $proofRoot 'app.log') -RedirectStandardError (Join-Path $proofRoot 'app-error.log')
    try {
        # The seed travels on stdin, not the command line, for the same
        # reason as TASK-0032/0033/0034: the absolute path is a search key
        # for the harness, never a value it exposes.
        $seedJson | node scripts/task0035-webview2.mjs $Port $variant $Phase
        if ($LASTEXITCODE -ne 0) { throw "TASK-0035: WebView2 proof failed at phase $Phase; inspect $proofRoot" }
    } finally {
        # A REAL close: the window is asked first, the process only stopped
        # if it refuses — and it is the process this script just started.
        if (-not $application.HasExited) {
            $null = $application.CloseMainWindow()
            if (-not $application.WaitForExit(15000)) {
                Write-Host "TASK-0035: la fenetre n'a pas repondu, arret du processus demarre ici"
                Stop-Process -Id $application.Id -ErrorAction SilentlyContinue
            }
        }
        $application.WaitForExit()
    }
}

Invoke-Phase -Phase 1

# The OS-level clipboard, read in THIS session, right after the app that
# wrote to it has really closed — the same clipboard
# `tauri-plugin-clipboard-manager` wrote to from inside the running app,
# via `map_copy_node_path`. Compared case-sensitively (`-ceq`), for the same
# reason `TASK-0035` C demands an exact copy: a case-insensitive match would
# not actually prove the text is byte-for-byte what Rust confined. Never
# printed to the console, a log, or anywhere but this one boolean.
$expectedCopiedPath = Join-Path (Join-Path $seed.absolutePath 'C') $seed.needleName
$copyClipboardMatchesExpectedPath = [bool]((Get-Clipboard) -ceq $expectedCopiedPath)
Remove-Variable expectedCopiedPath

Start-Sleep -Seconds 2
Invoke-Phase -Phase 2
Start-Sleep -Seconds 2
Invoke-Phase -Phase 3

$phase1 = Get-Content (Join-Path $proofRoot 'phase1.json') -Raw | ConvertFrom-Json
$phase2 = Get-Content (Join-Path $proofRoot 'phase2.json') -Raw | ConvertFrom-Json
$phase3 = Get-Content (Join-Path $proofRoot 'phase3.json') -Raw | ConvertFrom-Json
$fatal1 = [int](Get-Content (Join-Path $proofRoot 'phase1-fatal-count.json') -Raw)
$fatal2 = [int](Get-Content (Join-Path $proofRoot 'phase2-fatal-count.json') -Raw)
$fatal3 = [int](Get-Content (Join-Path $proofRoot 'phase3-fatal-count.json') -Raw)
$totalFatal = $fatal1 + $fatal2 + $fatal3

if (-not $copyClipboardMatchesExpectedPath) {
    throw "TASK-0035: Copier le chemin did not write the expected path to the clipboard"
}
if ($totalFatal -ne 0) {
    throw "TASK-0035: $totalFatal fatal console error(s) across the three phases"
}

$artifact = [ordered]@{
    task = 'TASK-0035'
    status = 'NONCANONICAL_ENGINEERING_EVIDENCE'
    engine = 'Windows Tauri / real WebView2'
    source = 'REAL_ROOT registered internally (task0035-seed-proof.py) -> map_node_children / map_copy_node_path / map_ui_preferences(_update) -> MapApp/DetailsPanel'
    realProcessRestarts = 2
    tree = [ordered]@{
        generatedByTheProofNotByTheUser = $true
        personalDataUsed               = $false
        indexedNodeCount               = $phase1.indexedNodeCount
        cDirectChildCount              = $seed.cDirectChildCount
    }
    panelVisibleByDefault                    = [bool]$phase1.panelVisibleByDefault
    childrenPagination                       = $phase1.childrenPagination
    pageForwardNoOverlap                     = [bool]$phase1.pageForwardNoOverlap
    pageBackwardExactRestore                 = [bool]$phase1.pageBackwardExactRestore
    childOutsideProjectionSyncsMapAndDetails = [bool]$phase1.childOutsideProjectionSyncsMapAndDetails
    revealSpawnSucceeded                     = [bool]$phase1.revealSpawnSucceeded
    copyClickSucceeded                       = [bool]$phase1.copyClickSucceeded
    copyClipboardMatchesExpectedPath         = $copyClipboardMatchesExpectedPath
    hiddenAfterToggle                        = [bool]$phase1.hiddenAfterToggle
    stillHiddenAfterRealRestart              = [bool]$phase2.stillHiddenAfterRestart
    visibleAfterToggle                       = [bool]$phase2.visibleAfterToggle
    stillVisibleAfterSecondRealRestart       = [bool]$phase3.stillVisibleAfterSecondRestart
    fatalConsoleErrors                       = $totalFatal
    absolutePathLeak                         = $false
    internalJargonLeak                       = $false
    historicalCommandsReregistered           = $false
    limits = @(
        'No personal brain: the analysed tree was generated by task0035-seed-proof.py and dies with the proof root',
        "map_reveal_node was invoked directly rather than also through a UI click, to avoid spawning a second visible Explorer window for the same fact; the button's own wiring is proven by DetailsPanel.test.tsx",
        'Copier le chemin was clicked for real; the clipboard comparison happens in this script, against the OS clipboard, and only the boolean match is kept — never the path',
        'Development workstation; not a modest-laptop acceptance test',
        'A real explorer.exe window may remain open after this run — TASK-0034/0035 forbid killing it globally, so it is left for Windows to manage'
    )
}

$artifact | ConvertTo-Json -Depth 6 | Set-Content -Path (Join-Path $repository 'docs/performance/runs/TASK-0035-webview2.json')
Write-Output 'TASK-0035: three real launches complete; artefact written to docs/performance/runs/TASK-0035-webview2.json'
